---
- name: Ensure SSH is installed and enabled
  ansible.builtin.service:
    name: sshd
    state: started
    enabled: true
  tags:
    - ssh

- name: Allow root login with SSH keys
  ansible.builtin.lineinfile:
    path: /etc/ssh/sshd_config
    regexp: "^#?PermitRootLogin"
    line: "PermitRootLogin prohibit-password"
    validate: /usr/sbin/sshd -T -f %s
  notify: Restart sshd
  tags:
    - ssh

- name: Ensure root .ssh directory exists
  ansible.builtin.file:
    path: /root/.ssh
    state: directory
    owner: root
    group: root
    mode: "0700"
  tags:
    - ssh

- name: Set authorized_keys for root from variable
  ansible.builtin.copy:
    content: "{{ secret_ssh_authorized_keys | join('\n') }}\n"
    dest: /root/.ssh/authorized_keys
    owner: root
    group: root
    mode: "0600"
  tags:
    - ssh
