---
- name: Ensure SSH is installed and enabled
  ansible.builtin.service:
    name: sshd
    state: started
    enabled: yes

- name: Allow root login with SSH keys
  ansible.builtin.lineinfile:
    path: /etc/ssh/sshd_config
    regexp: "^#?PermitRootLogin"
    line: "PermitRootLogin prohibit-password"
    validate: /usr/sbin/sshd -T -f %s
  notify: Restart sshd

- name: Ensure root .ssh directory exists
  ansible.builtin.file:
    path: /root/.ssh
    state: directory
    owner: root
    group: root
    mode: "0700"

- name: Copy authorized_keys for root
  ansible.builtin.copy:
    src: authorized_keys
    dest: /root/.ssh/authorized_keys
    owner: root
    group: root
    mode: "0600"
