apiVersion: pocketid.internal/v1alpha1
kind: PocketIDOIDCClient
metadata:
  name: pomerium
  namespace: {{ .Release.Namespace }}
spec:
  name: "dray.id.au"
  isPublic: false
  callbackUrls:
    - https://authenticate.{{ .Values.domain }}/oauth2/callback
