apiVersion: v1
kind: Service
metadata:
  name: pomerium-proxy-tailscale
  namespace: {{ .Release.Namespace }}
  annotations:
    tailscale.com/hostname: ingress
spec:
  type: LoadBalancer
  loadBalancerClass: tailscale
  selector:
    app.kubernetes.io/name: pomerium-proxy
    app.kubernetes.io/instance: pomerium
  ports:
    - name: https
      port: 443
      targetPort: 443
      protocol: TCP
    - name: http
      port: 80
      targetPort: 80
      protocol: TCP
