apiVersion: v2
name: metallb-config
description: A Helm chart for MetalLB configuration
type: application
version: 0.1.0
appVersion: "0.15.0"
dependencies:
  - name: metallb
    version: "0.15.0"
    repository: "https://metallb.github.io/metallb"
