---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: mqtt-homeassistant-credentials
  namespace: home-automation
spec:
  encryptedData:
    password: AgB9NEUgxY98Z7DTXvD1zlzE8Il8pgMgWP+tO7bgSBAlzf4xTCxDNJchx7IxZpBWOL7+ccTR65k/WGVq9GN14xCO3A7ode34td/Mu1C+wCT4dhH3Rcxuvtv+V3IkYnKDYrQ3c17bWpoI8Q/RxUKQ6te6RoU9FLcHPmGsJ8RfP1yDfg5Kb35UfXeubG56rp69fMIxl0qfoD/RIDmhsrBkS9Gq5zY7wO1l1LTDGtVzNnGw5LsgXsJApslIWW1sTfz6sycYLSVwR3/EaOPXeHzWwRwB11h3Qq0SUL2hYol31f6WycmSg3b7L9lH1nY3US2+usQTzC7zilpR9awJBdqqgv73Za7cVn6GE4QDNXTiqh2EisT5gehOa8dPDgLazJFuQqNjsWXXmmqqH3mdVy7mZWnjfLpTMBz4vXDV/P5D9ttwHYSURE1tgpVfGLHpdBs6mpm3NOWVCST5ENe8RuRn+6mEMDZykN8PIecDkzDDUrDiiQkRO73ZPEQ7qrt+PF7kTshep3rx2SUmTZEH3vshrk0rfc6UOaOA90TFbTdaMVzdcQ+v+OACtIY4X/EBl8HtbtcSuxtpXeTvzV+99wM8GOeYe89woT1l2HrmrT0FJI8M6oWVHmVS4/6XKVYiomk/yitFwT/aDX0iT8+Sj80HNaws0uz5OBuaPB7nYwCIJpIvYWrP0aJsutQocm5xW6TEvydJ6ctnvjcXGjD4B0NTFFrK/pgXUp1ytnjvfK4voXoTbA==
    username: AgBJ7yTGT/rVDrP9EAd9trTiltIuY+eVIvY60blXUnWBumSYxDA+9FIp4hkku/jsqa3AqSXbHkJc8JmDEx0pwaNAD2kBEn+TUuHFWiT4LoBqibB+J+yvpHcNVJJYa4TgKjSijhfU77sIuQMC3xC5cttJmWBwnD0uffFVqGdKJ8nTf2E3krW4rs6bw+GzSMgVEdXaLb81XfwTRQ3dvWN9YEi45LpKIXr6qPKoIPExV6/pTCP5hrcgys82PKc92lcLwra8OGskgiIH6auw9TLbCkmEBVyynZUbHP9bJv0kgqatqtHRzj0EFNmXif6bfk55u8yI9uCJq6P4PnURwFgZg7vMDZgitq3yMGF0tYqdAP4DwOIf1zvW9+ufgHuHtYzYpigR2UADc50GIajDpqzvYtTALRcOBYypTPirxTlDUgG5JeNF5CdOarMSuea0BGYgxvZ1todO9P/7P/T98RjlAuomRQOFdT9YuuNhW+lngErpzzgGSAemysqoTNeagIu3SiaikaWO4PMVJUJ3kMaw/cooa8AWI6H4UNFdtDLiDWN3eXNoiHtlvt68L90ryxyD1CsEz4xSTKHV/HnuH8p3yi/XrJI5WiSB8a292M13X2Il2xpoC6nLwuxIpvNhQd66lZZU1f7gvYksPYv+rfD80dS5P1MAIyEVk3DSUGvbt2JZISEmJ4tN1CcsgL1pJYllM4Ymf+pW0EXUikYHSMPH
  template:
    metadata:
      name: mqtt-homeassistant-credentials
      namespace: home-automation
---
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: mqtt-z2m-credentials
  namespace: home-automation
spec:
  encryptedData:
    password: AgAnYfcMHAXN9OfA/k+uAANyA+NtPrc3U6tdFT7x807HXxtRXZ3UCgIPUeNFDsj6oivoc7ctx58rjBZwsnY3sWsJF+5C23Dvrldw+dPyf1y2iyKCXH8lfpdt9WMXbg//1s9yJ5E9PtlrSxJk6y80gIpNtVxv/cajfOuhqLe76W1i6HYxSUhRZ7I6zs9X++jF4Qt1bj5VbNkak7OdE+9QAPPTz6MulepuTmPJSPMiqXswOB9Nxy+SclXQJlVa7jUNmWxmN0B+dxNygkaVhn1r7ZBBqzpuRLACGmttZMxQSS9C17MXNup2r5GS+DrJcQtNlezfPvKmd7Muxqdugae+meqzJUvdWduEBVmrlD+Z+MgHfnH+3AcGpPR7WCh1NdJLa3SterZbEHqM99e+5fSi09Ez/RDbuxbTXrHvPH53fUmEr4/6NNK6tEraI8BZbZ415pAgt/Tc3IXn/RIHNKk/VuecuVGbvh8ZbSg6ByGNQBkN4hRwpFbkD+AsPSaimWhpTqYd2wLR7uYKkkgPjy6vSk9cxggEmle166AcllnVyZNanYlxAr0jB55moBWW/A76ipgypuCcogySRY36mcohOAVOSIu138BwKZwegWJPYuTVZQX0DbEFqChy8eyAsE2jCJDkRuqEocADb5p+nmf/uoO7h55C97zd9qbi1DoZo7Th2WsfEKlNcSYXX9YY0/v/Q+uYnSRLYo9gqb5O708AEMDMushKFQT+U10hagYf2rtT/w==
    username: AgCs4LYeZP0oRkBbqfUG6+sBE9fpz7EEF0M+0TQW5mU7j+oXWb9cmY6kBEn3Qe6v5V2dt1XXLtWPg+GZqhAF5pU7J+fqmxEc2V4brfCPgPdWGT337dF2FCqjOIBxmNnNr9u1hC6xyHnQGuTRHBVbeYTRN1o+pQ8EfOfrYwyx/KVTGtK/KTXVIKmBvZVr4I0ppxNH0qvcYrt9pqpSaToMRrRefbWlNwPXTcJBYBvSwx7goWjOwsHCET9b5okE17VEOujdy9CfgCzyMOIJiZ3t8RIHfGubQnitUU3XtaG7nSZA/A7LhtiIHV8GQ45MbnnunWH+Uhs+W2Ub9JXPAr6hvMNZPGb9UCmSh6IPZTzE15rZHnpIkcZeivdkBgRL0qWwMw0AKw0NzhIV4J9bDhvAq55Ve6dxEkta6JYgkzKhcMqdcd+uhU6FO/tRpzGAxFkPj2wQ9DRantAxT1rZY6vuLp/PnBIDk0SW9+29iw6JqoJK/D9uG7a/fE43h4zMHQ2ov09+SIDeJaKih2gEFBgFY/LfIS0LCsCAkkPK4i7Zn+eootGv9CeSkk5hoF4ZNMX3JcnRXMgfJ/pWiS5HQSRvSpWPwqfn1Dl8Dm7y3mbr9vL39tHY7Mo+jfWnFk+HeQYpkJdynZ/w5w7wmTtjKf6HN3bwPCSXQZtbTypec2Ivh6394DR2IB56jQr8KTDauaTIOalYTzR9CQro/pSRoA==
  template:
    metadata:
      name: mqtt-z2m-credentials
      namespace: home-automation
---
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: mqtt-test-credentials
  namespace: home-automation
spec:
  encryptedData:
    password: AgB/nUdULXjiOc7CmbY3h2p/ut5Qy6y1gMtbg56uWOakziz4sAQM9mtHctnvX9zAQDVq4lvrsvH46qdJBMhbAcZb1E7B2yK0ogKF2Innh+jtVdG3WpXupJibHDF0sHKW9c+BPwong8BrLGS0+Tfsiaux8YlscQ0l6IUqJ9wswmfY135oMT6dSaUwjfkD0IXWsaehgKOEYREGsBAYpua2hC49lgr/i3xNctQ/eaUOyHlCbxp4tAtrfcLkCLv6SDiYXiXIBbvJ6cc+DxHB2uLDevkN6YrQSaJyMhTu7ytsaXVxavwUoTx8YfTOxV9EUH/mZ5CwG7S6LqLDKNxFWsTqGGPHbP9Luw2/iP8JgL1byDja0yiHvQEayEVsZt6Ysyn7yq6APFxr0NfnzkSEaUrjo+GdrPcxrBv+qRNmFbawpVPZJA6D8n0ytsqCvu/5/OJTsHqlt7Qr0G4ZBs1erXk6h5Eb6YpkBqMNCdsep0NGw1oUNQTLgVKEeLpf2voDsI3jkYTEiAfSqNIkhGFBIxwHNTdgaSGBzBHlg3cYBCTi2IFoQe+WfxaWfuOlwWkccLqSdGrx++V43B+h7pJ9KwfUtFMC5s2LKBzY1VlfrbQoNAPXQBeKEIKPb020c/RpkO8YIas+ozz9B0nc4iVfNcRxQ64m0N4spNVg0MkSiiHN5Rk8E5Ec8khsOOicEiFE8Pr821UglsFd5J5QWLAoSn7eb8lRBo2zkarS/cGwbrR0v280iw==
    username: AgB2lraQG3TRCByJA9B/Je48Cg4IzVNm2LP/N+9B0hVYFSNzbRhztZ3riMweiPSd5wuwgcYksZPo+QJzLZdWodeQHVWqD21HgRKViLJO97vpF9VU5Hyx6kC30TpspjWlNl+c+JZgGsUDG1e98ci+E7ZmlOD6QbonH1d1LjLTzW9NQofNR8l/Gg/JEAq8Ks236e4VwAsdR0pYAVdXWgJDJbrP/b+bVSw3d7I7nWb5JqS5rc2MWPq9BFMo4fI47mAtiQF+ZubODMvztcGnoxmp7ykXdJCqBkrmqDf9rzHN6qiDnxCKPuTaebgfZXhndkl4VJ5KyJfLU8RyLvYwxwEBDG4kjCmIUaJ8kXlPcBJ44L5ph11iZoaWdMLjek/+1nGloqmvAPiDA6/XVTa/n5XeyMCqx97xSevllR8pzI9Spt6zzjTc4zb+mNYPw2NGd2lgQxdDQQH1jSmlbXSWFqEEwWBh2HkjVkxBXa6IMrGmt5z4lyi8ALxPWaUFhnRq3fMg5cW5qhR0uz87V1kr6APh4vAQn//04xeDNR++UXBIikHsThStHZdwsDCzhdXAwLhFfUufbB5/Z4R/t43yEMQQkr/El/UjVNTXQhtlwHHJnOSM/GPXzQwIvherdMm2Hpuw1FotfI0IlRZVzCZ3D5BvmaaZaaP3/vL5mc6f8F8huoLWJ7hwzE6GRz16W3JwOPcw4gWZxT+S
  template:
    metadata:
      name: mqtt-test-credentials
      namespace: home-automation
