---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: mqtt-homeassistant-credentials
  namespace: home-automation
spec:
  encryptedData:
    password: AgA3+fcBgjfGxk9hJoW0TL8tNsE21QNXeHce5sOkvaqc4F4jjyKxhK2Kw8PXTcpitv/OPYg/p6APnji5Vk9Kb4y6XY2O8v3gcm+N9I0SBhTiv7KOYRlDU0Uv4gecvrCZOFX/vgX9fyJI+HFNCz3p33YV7sBEG8SF8BK8HuopiROzfih7vwZGZJwfdX7vdpwHyDLyNVQVDCTLv3twPqy3gUE1ZsPb2VjbyWhh/ZlOMPA6wnqwCjLOApo+OfJK721KkFE1ZkcHbk3cnburm3hEJ+ba6eVsHO2IZ1nQFJP0UjMBvnUayfGXbZSh05oXHdR0n2iF21p/0kMucySMXWT/0pynUtafxBpgUAShsMJYJOv8IKn+Alpwzc/0v+G81bYcqoeM4b33PVlL3yw5T4qVuhCFr2WY7iQaprq6osiNEWaGTQWk4YOZupZfCpCFrG6nYizY4tP9yoOyG4YmCNq+fDbLbRVdfM5c9Aq0WgOrqQhqjRnkK7Co2kODC75jLlF1iXc6kX/s4PpGdD2Cx3lgij1Tk3rToBFSDAYj5INa25ObOcz5dqEoJdlG/ufUzoZJ5T4s3vTLImjdKRw76CWXfSMhft43jlcofhyoI0e5ws/7x4oThWSEbujm+hvPw7xIfx4t5f95zyglQ4r7yMuz76AMOklVT/eTfcMOA8ShJQfScU/bKVTb6kiwHzSrK7Uxuf2btNsWObLfWN/heeOFrqFC/Goqg6ZHttmw1M7Zk+W7lg==
    username: AgCM0JJW7w6qycUV8Kvb7h7eiSR/UoaVSrKD7YI0QUA05pVDmDw+fPNr+ghXh46OyIf7yMjRM/EdKJ/Bm6sTrA2y/c7XBFIYf5+hBwimwsKXLAkCwCamKwEVuSFzsxpVGOVDp9gOA45gfcs5R6zSThCAWRexh2KlCIgJGPK3nDtWHd0lZYhrkr+42j7CUhBUnSrRrw7GNGgO2zlC0dc3489jEJ2TOVVfd9Se/yOpEaYRrBPRIPGgredCEf9caWvUsZKno1NgZnDMysrry45yUM/1JGFviA7yf8FW6dU9m4z5eMhWs2x1OdxNs2UCQoRoPDs90AcyFZnoea/bjvPCsAFBCxaLZw+CmHNqLIm7HpAMHUqtzxwYTkDfmYV2926bx9W+iosA1+LkU5Po/qFIdGbstdIEbHIbkgT7bnq8wIvUbECfRxqYQdOQbl7IXlIXxF8NJRXcC2KI5e9q6AND7XBp5+e7WV+gWsyYPJsQrcV6mDuikRn8fy2zByXFgbzuq9lKBSrw6kOT7GY4B76V+3+5S9lZUD/47Zr8bsI+7OOkNdOkFQTcbuKP5UrhqG8LNAOW0UL45s5UTkterPyNCmJl79/dT8waEbDiYbSUOz8YBiBOh6iXJL+BydM18Xy2nY8Esvca62tqzeiqSNAcrU7+nEhLpObiV1kj5LeoQhScGf/Nm6cylSQaUH/3zar35uTUkLtWhIOrQURludFD
  template:
    metadata:
      name: mqtt-homeassistant-credentials
      namespace: home-automation
---
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: mqtt-z2m-credentials
  namespace: home-automation
spec:
  encryptedData:
    password: AgCqcCPerBqREhkufr2li0JroMzfxyhbaySf1XpzCK816F7NjVBmp3/Z4W2phWeN+MRtmHSWoPJNLsR11G1lFrxGAA9gB2ua5YNapodiE52DrUUsPI7Zvrg2ALnn3/FIhxElXEZ5LeImbuR9PTu3YPoY46iHy2lpfQucYXqAp1np3zUZ27+CSEmHfA/vFJH969dUC/m5By8ncitUJRfLGnOsTUZUgEneno9kXIpBWV7G6PiwoO7NwQDG+PMcDFdcrIss+ojdd1eWhw6tw4NA+w+SNj36SrrRM2otZRsnefEH8O7ld+2CnhFTk3T9G4SrQBGNT41YERKwpwiPOdyHdGf33Ad3JasIap0zaiIEHZLG87FodqGjog1G7trBRtvp0SKTGWnIo9AC78bW/umIKacBB3IR7/teOE9b+gQIjidg0JSt68PvRQaV2ZRMPloZMAqWTjRVZplYDqfJcJ2e2DqU9ReM1bLN5Qf3Wav2Y9JJdrx8YlqSjXAKDWD5D/vm9cvX51QyvKmeQVVmYtVokNld+3poSIJf+T0dKCy3WDFC8r5eFpNj1cV85WvYSDvbkDSFjeFd2WZ4OhQ/ipwdvPJ4kzH4XD2NCPIEanlk/vF3hy2P3Q8oZyourD2X4vhSwBsMPIdMqC6HFbvkwbnvQoudIzL7K1G/6pApQO85esbO2J0EfgVfkCRY5iYgg+1QRvJiyn41pGdaSPhQewZXH8kmzqyaHCJ7YTcSLouUEgouzQ==
    username: AgAR3dBfnC9qt3vo2FURkv+2ViQMsQ8UavbhosVvHmWUD9tyjVxQfcsDm4J5VBPIodLXBr4GtpjzHIRUoNh+iRyMAV4xnabWw93kxouHwgxuWOfx3DlcQv5uGBe8VExDWXwOUMxbX/2pmGXhfZhnLbkgG+Nc7Zm1h9nCPFJnQ4hwwYcLFos6f47b+obiO445TDodOZAyprp6Raxxo4P4Q3VZ1JsjOCyJkwCLSLw8QydSI5njCo5AowgHjsO2bHbNFKlhiY0DKSZO3otRiM5giBBx0MprMIi8XfNxXnHyoZsMWxDFGRhLBQ6EYC9KfCfR4mN6ZXkqWzuNhtgLbEGJN8GbVEHNQH3SxHG5YWtXMrQzllqfLUL8H1esH2OlPnd5LKI3mQYE4ZTGr31OkbKM+ApMZUrMOnMoLGUP97ro3/feye5qf2lRQ1mZzcZXHs4LRD7FIgF8mOsMzY44CKBy1EbgwHgK/r9OORaSaYE3rLHgMpLR55DWxFFnE7fLkWFa8UzPnQ3Ztr5TvQazKwqa2p9l39oHNezdlYhKgk9/qqnA3Bn9b7ARvzOH4COC0TZzgPMI9I3LudQtBngaHgwqLzVsWe4BTpqmoRxqBZD2ALcuGLudtQ2wCxvlcxNQMAJf+9OPR6uIsDQqUaKfPGIB7/KrIYgnD+tLGgQ5p60GwzqeWrXsZ7+9p1M/D+cPpHfLB7+5gQhkNswCCc7o7A==
  template:
    metadata:
      name: mqtt-z2m-credentials
      namespace: home-automation
---
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: mqtt-test-credentials
  namespace: home-automation
spec:
  encryptedData:
    password: AgBgI4Wsy0rE7hCG97HHb8JJRpxJ1MB26Vm2Qa2nHaFdZJsZ/5unhFMFTa+H0pCIqjr0W4wKrxgOD80sqJtgNCfdBewYbIOpOx82Zqm/1crYz31YkBxnDcav58sNlsc5qEvxiJyYTNaSPChLpV9bmyokCUlx+kyfJ9EbLMHlWIDhySWSMwV2UjHE/iyhB9MKY0x54rBTJ7zUw67mZqkRCIBnKdle5ZM9u3FfOiCdsGMwKEsJkpGwhG0zzLQEgLM6bNA4ZKWCQshGEoxd1+eTsY7XrK3Mg7O11lXTIgnORgdVLkx8pZxVAe6O0m9BSFkK5f/Dk1s17IaDsJ2KC3baW3ze0gWUPF1XFRJrHXYuLKfajxzf+iYdj+/BA80BCNqT5GDMUj7CCOP4Gy4O3mIhtexgH9q5eoM3i4f6khcFbGlwd7QJ3dSsyqLiJisdRYhRLYC7ZsFDXXgiuHK79K7Vrn5e7//bOj8ccDXTuGu8+zjGS4NVaaai6XW46HzKIYZRi0C8Hp6+QeTdQfi+2HeSzkg3/+Xr7fTjWN4Q0YJrRGLAW1H89UNGeO0JMLVYEt4MlkCr1MFma9WEIvaooigJSf6GujbrdgBy7DJag8OBVZ2pcqod/5EHk+djYSrS4nhXcxFytZuaXEiOaErEwqX/IKa0gytLvkpW1E0bVPzxrwysP+EvCPUh2uWvAIAQTu2AF9POetZEp2fNDFNM3VrEsMm7EYtwq3pVqFvlPLHBYIB5Kg==
    username: AgC22QABI+lioCLcr9b7nvchDVqVZDYr8SZPXHYO4HQU1KSgeBNpJjTveWzcAN8J5HamBxkTtZJdpufuvLNOfpbTQrFhCoJxiWLnSV/Hjvk35q+aUydKTpMl+Qb0pjzDahK3vYRxaiIpC+koLpcxJD8+GE4dNfH5xAtC5prXvrr91XGp4JSf2XpA/yvjIzPpgVu91M2B5OiWLTqKB4aMK/kff/hnp0uUh/Rkav4G0yFjJj7xlXeW8k/D4R2YF327BnPW+G0w8aeBHl+4bAqv7tE0P0d0IKsZ78SdJgWHjyWXqqtJf+guq6HEVsdnFJaKb0SOsGFBT+qhZuM9ObGGTL49eyriQcC4I6Zyc2Mj/gTloOYlOFmM7heM/JYiCWRrQcsOm99p8zeSo1Mx7H3b//RKnkr+UDEdOdQRwKC2H0aod5UT1LQx2gUGcIbFkUjq55A4wyrMHrIgqWrahPohy5TyVzSrLoxjW/TICYe5gTKxxjWgyen93T99xVNrCc/yv2xneXgFYJ26JidXR8W9dRR/7//ENIymZXFgbM1tDUgJibopkYrbXAFy6xJ7+Zzc6bROvz2/oBmN6iLRMQxHKvj9BwWQx2EZ0PUQKnSvkkFKw+yygQBV7rJ1oDVhsuqIXz7L9bydu0NrAC7kT//8z6hXCy1aLcshBF6dlb3MI7J5mx9Jcrfqm5oXxMNOZNT40gcwqNhi
  template:
    metadata:
      name: mqtt-test-credentials
      namespace: home-automation
