---
# tasks for users role
- name: Install zsh
  ansible.builtin.package:
    name: zsh
    state: present
  tags: users

- name: Ensure system users exist
  ansible.builtin.user:
    name: "{{ item.name }}"
    state: present
    shell: /usr/bin/zsh
    uid: "{{ item.uid | default(omit) }}"
    password: "{{ item.password | default(omit) | password_hash('sha512') }}"
    groups: "{{ item.groups | default(omit) }}"
  loop: "{{ users }}"
  loop_control:
    label: "{{ item.name }}"
  tags: users
