cloudflare_api_token: ENC[AES256_GCM,data:xOnVkLUCOSh30mWAVQASJM3cnmTTHXLK6qFkJ9T77dCPP8AnsIKXdw==,iv:wtRXPunj5Hd99JSmKwegKANMimDvXjny75M8eOuRy0o=,tag:M1Y/XwFDXGpHNV/qZn5Nqw==,type:str]
email_password: ENC[AES256_GCM,data:F/bFPer+kgans0o5dKE3CNYrKSnXO3n7QMsWDfftHLYwcknI8/eeUEMDtwE=,iv:zPMJuXECPeOefjkVek2G+No4QzDy1bSMbw3iEeVV9Ek=,tag:X0Kk/+GYpbDwN/pQ8q9HgA==,type:str]
email_username: ENC[AES256_GCM,data:RfArDjJwwe2YZKsK9t8vRF5T/ec=,iv:vZxrX9ozZBz7CmB94r7+KT6l/aHrJJwdJ8hWoCEN2NY=,tag:WBJPVzCwzcY0jy0Ii3v41Q==,type:str]
tinyauth_oauth_client_id: ENC[AES256_GCM,data:M1pX1TDdKc/OIft84+bJtPkM54ojK54hx28V0oYzZuHSpo+L,iv:lK+SThu2rS6RboNIhkRGK4+L0xQE8uszbFKZwJ6+WeQ=,tag:S27A4Ej/dFan/hePiyxHFw==,type:str]
tinyauth_oauth_client_secret: ENC[AES256_GCM,data:ufqezr8HrwBE3p5FolhHKQVY2f+Q/rh3n8QwfXKeaRQ=,iv:1WIGmnhvuB1kgLVzidDXQWIvG6G3Li7VNvo3OJLdQK0=,tag:xVRQj6x3AxLcTdn9GdLwGA==,type:str]
pocketid_encryption_key: ENC[AES256_GCM,data:jy3Zqymope2CC9tDw2uoY6UfmC05NVJy0pB6c2mvWfd/GNd7wx3Vi6JYRLM=,iv:g4fwQ7YmDFQ3ksubR4MtY0vZfWCJasHrj/4mgUvzQcM=,tag:NLRLVudO5Zyg82ntN1P5RA==,type:str]
tinyauth_secret_key: ENC[AES256_GCM,data:DcCNixPPCEvQbdyk/oi/P2ZXJu8tV3K9CMEYTi4C92N533x6pFtWeI0VVcA=,iv:on+7fViVIfZfTzAd8QuaJhYVb9oHrT5phhwjnlbdw+U=,tag:Itx1WMesiXLMHvh/h2AfaQ==,type:str]
sops:
    age:
        - recipient: age1me7as6xhtzy8eqsqlxgf0v6eq692nstv69eg3hjfrksksm4cm9wspmspwz
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBWdzJaZTNETFR6NkY5b1Bu
            L0lJbXd6dHlCZUhlejVHSnMzWnJpbldjOWtvCllMVnR5eHlRbTJOU0J3RVc0amt3
            bkpteHdmQ2ZkSFBpOUdnbG4yYmtuQzQKLS0tIFNWeUUwSUhiKzJSU1pnWDN4V0VC
            dEMzVlBoNTlieTZvaEtaeFBuYnR2YXMK79lsUkTyGvxqHigV21uDrqeGJUCvCZbq
            dOWKE8w6e9HogW/NKnaZrMRDW1BPZhqgQRzwSnIwbBkVd5TxrnT4Lw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-19T03:37:34Z"
    mac: ENC[AES256_GCM,data:MFE6i8ouiT+1pl1UamVTlmQax72XMbv/j+B1mBvB8bxiCA/EAtR+Ftcb1tndYf8iDIYqwNdcofWv0Pl/ipHnbWbpM8yjXaYqjRK0cLSNrMnsjRVCicaPcLFZ+aFOA9wQzH4yUTa4CxeJWd50yigP/rHPcCP/d0bbprMI13Xlv2g=,iv:ht6En+rLq8m0aw4yHQPurDFyCewrgHdPiVQ5iV+8PRw=,tag:aY2o65CX86TcnRgpGM4YhQ==,type:str]
    encrypted_regex: .
    version: 3.12.1
