apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-vault-plugin-helm
  namespace: argocd
data:
  plugin.yaml: |
    apiVersion: argoproj.io/v1alpha1
    kind: ConfigManagementPlugin
    metadata:
      name: argocd-vault-plugin-helm
    spec:
      allowConcurrency: true
      generate:
        command: ["sh", "-c"]
        # 1. Write the HELM_VALUES env var to a temporary file
        # 2. Run helm template using global values and the temp values file
        # 3. Pipe to AVP for decryption
        args: |
          if [ -n "$HELM_VALUES" ]; then
            echo "$HELM_VALUES" > /tmp/app-values.yaml
            /custom-tools/helm template $ARGOCD_APP_NAME . -f ../../values/global.yaml -f /tmp/app-values.yaml | /custom-tools/argocd-vault-plugin generate -
          else
            /custom-tools/helm template $ARGOCD_APP_NAME . -f ../../values/global.yaml | /custom-tools/argocd-vault-plugin generate -
          fi
