apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: sops-age
spec:
  provider:
    sops:
      age:
        secretRef:
          name: sops-age
          namespace: external-secrets
          key: age.agekey
