apiVersion: longhorn.io/v1beta2
kind: Volume
metadata:
  name: mail-proxy-spool
  namespace: longhorn-system
spec:
  size: {{ mul .Values.spoolVolumeSizeMi 1024 | mul 1024 | quote }}
  numberOfReplicas: 1
  dataLocality: best-effort
  accessMode: rwo
  frontend: blockdev
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: mail-proxy-spool
spec:
  capacity:
    storage: {{ .Values.spoolVolumeSizeMi }}Mi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: longhorn
  csi:
    driver: driver.longhorn.io
    fsType: ext4
    volumeHandle: mail-proxy-spool
    volumeAttributes:
      numberOfReplicas: "1"
      dataLocality: best-effort
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mail-proxy-spool
  namespace: {{ .Release.Namespace }}
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn
  volumeName: mail-proxy-spool
  resources:
    requests:
      storage: {{ .Values.spoolVolumeSizeMi }}Mi
