{{- include "common.ingress" (dict "ctx" . "name" "shelfmark" "type" "traefik-private" "port" 8084 "auth" true) }}
---
{{- include "common.ingress" (dict "ctx" . "name" "shelfmark" "type" "traefik-public" "port" 8084 "auth" true) }}
