{{ include "common.pomeriumIngress" (dict
  "ctx" .
  "name" "sabnzbd"
  "port" 8080
  "allowedUsers" "admin"
) }}
---
{{ include "common.pomeriumIngress" (dict
  "ctx" .
  "name" "sabnzbd-api"
  "subdomain" "sabnzbd"
  "port" 8080
  "path" "/api"
  "allowedUsers" "all"
) }}
