{{- include "common.ingress" (dict "ctx" . "name" "sabnzbd" "type" "traefik-private" "port" 8080 "auth" true) }}
---
{{- include "common.ingress" (dict "ctx" . "name" "sabnzbd" "type" "traefik-private" "port" 8080 "path" "/api") }}
