apiVersion: apps/v1
kind: Deployment
metadata:
  name: audiobookshelf
  namespace: {{ .Release.Namespace }}
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: audiobookshelf
  template:
    metadata:
      labels:
        app: audiobookshelf
    spec:
      securityContext:
        fsGroup: {{ .Values.PGID }}
        fsGroupChangePolicy: OnRootMismatch
      containers:
        - name: audiobookshelf
          image: "{{ .Values.images.app.repository }}:{{ .Values.images.app.tag }}"
          imagePullPolicy: {{ .Values.images.app.pullPolicy }}
          ports:
            - containerPort: 80
          env:
            - name: TZ
              value: {{ .Values.TZ }}
          securityContext:
            allowPrivilegeEscalation: false
            runAsNonRoot: true
            runAsUser: {{ .Values.PUID }}
            runAsGroup: {{ .Values.PGID }}
            capabilities:
              drop: ["ALL"]
          volumeMounts:
            - name: config
              mountPath: /config
            - name: metadata
              mountPath: /metadata
            - name: audiobooks
              mountPath: /audiobooks
            - name: podcasts
              mountPath: /podcasts
      volumes:
        - name: config
          persistentVolumeClaim:
            claimName: audiobookshelf-config
        - name: metadata
          persistentVolumeClaim:
            claimName: audiobookshelf-metadata
        - name: audiobooks
          nfs:
            server: {{ .Values.network.storageServer }}
            path: {{ .Values.mediaPaths.audiobooks }}
        - name: podcasts
          nfs:
            server: {{ .Values.network.storageServer }}
            path: {{ .Values.mediaPaths.podcasts }}
