{{- include "common.longhornVolume" (dict "ctx" . "name" "audiobookshelf-config-v2" "sizeGi" .Values.configVolumeSizeGi "dataEngine" "v2") }}
---
{{- include "common.longhornVolume" (dict "ctx" . "name" "audiobookshelf-metadata-v2" "sizeGi" .Values.metadataVolumeSizeGi "dataEngine" "v2") }}
