{{- include "common.longhornVolume" (dict "ctx" . "name" "audiobookshelf-config" "sizeGi" .Values.configVolumeSizeGi) -}}
{{- include "common.longhornVolume" (dict "ctx" . "name" "audiobookshelf-metadata" "sizeGi" .Values.metadataVolumeSizeGi) -}}
