apiVersion: v1
kind: ConfigMap
metadata:
  name: tinyauth-config
  namespace: {{ .Release.Namespace }}
data:
  TINYAUTH_OAUTH_PROVIDERS_POCKETID_REDIRECTURL: "https://tinyauth.{{ .Values.domain }}/api/oauth/callback/pocketid"
  TINYAUTH_OAUTH_PROVIDERS_POCKETID_SCOPES: "openid profile email"
  TINYAUTH_OAUTH_AUTOREDIRECT: "true"
  TINYAUTH_AUTH_SECURECOOKIE: "true"
  TINYAUTH_APPURL: "https://tinyauth.{{ .Values.domain }}"
