apiVersion: apps/v1
kind: Deployment
metadata:
  name: tinyauth
  namespace: {{ .Release.Namespace }}
  labels:
    app: tinyauth
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tinyauth
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: tinyauth
    spec:
      containers:
        - name: tinyauth
          image: "{{ .Values.images.tinyauth.repository }}:{{ .Values.images.tinyauth.tag }}"
          imagePullPolicy: {{ .Values.images.tinyauth.pullPolicy }}
          ports:
            - containerPort: 3000
          envFrom:
            - configMapRef:
                name: tinyauth-config
          env:
            - name: TINYAUTH_OAUTH_PROVIDERS_POCKETID_CLIENTID
              valueFrom:
                secretKeyRef:
                  name: tinyauth-oidc-credentials
                  key: client_id
            - name: TINYAUTH_OAUTH_PROVIDERS_POCKETID_CLIENTSECRET
              valueFrom:
                secretKeyRef:
                  name: tinyauth-oidc-credentials
                  key: client_secret
            - name: TINYAUTH_OAUTH_PROVIDERS_POCKETID_AUTHURL
              valueFrom:
                secretKeyRef:
                  name: tinyauth-oidc-credentials
                  key: authorization_url
            - name: TINYAUTH_OAUTH_PROVIDERS_POCKETID_TOKENURL
              valueFrom:
                secretKeyRef:
                  name: tinyauth-oidc-credentials
                  key: token_url
            - name: TINYAUTH_OAUTH_PROVIDERS_POCKETID_USERINFOURL
              valueFrom:
                secretKeyRef:
                  name: tinyauth-oidc-credentials
                  key: userinfo_url
            - name: SECRET
              valueFrom:
                secretKeyRef:
                  name: tinyauth-key
                  key: secretKey
          volumeMounts:
            - name: data
              mountPath: /data
          livenessProbe:
            httpGet:
              path: /api/healthz
              port: 3000
          readinessProbe:
            httpGet:
              path: /api/healthz
              port: 3000
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: tinyauth-data
