{{- include "common.ingress" (dict "ctx" . "name" "tinyauth" "port" 3000 "type" "traefik-private") }}
---
{{- include "common.ingress" (dict "ctx" . "name" "tinyauth" "port" 3000 "type" "traefik-public") }}
