# Traefik ForwardAuth middleware - deployed in both ingress controller namespaces
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: tinyauth
  namespace: traefik-public
spec:
  forwardAuth:
    address: http://tinyauth.{{ .Release.Namespace }}.svc.cluster.local:3000/api/auth/traefik
    maxResponseBodySize: 102400
    authResponseHeaders:
      - remote-user
---
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: tinyauth
  namespace: traefik-private
spec:
  forwardAuth:
    address: http://tinyauth.{{ .Release.Namespace }}.svc.cluster.local:3000/api/auth/traefik
    maxResponseBodySize: 102400
    authResponseHeaders:
      - remote-user
