---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: tinyauth-key
  namespace: auth
spec:
  encryptedData:
    secretKey: AgBOGnmZmPOxVMUSuKvurVgHSsLzrFKXxX3hjkO1Guk0kCwlRiMIz3H2nhrpHI6elPrHbrZdZ1zIbTKNsOC2/8eoCSYI33WYdAo+GpghaYv2NQKKJx1/63XRbMrU2diRggs/0SLaPOhWXcUnpAtMxLhwrfyTGijJ8/QZMr4odlMPui5QY3/KBIfbGmMswmgy3ppiUt8Ox4s6Sl61A1TyO2kF++prtLpGptb7SehpfFm7lVjmzQ5m1fa5Yx/SV5cO3yCxCl7EgO/jcDEnW+i3C5Mij3/d+mGQy0yFzF1NCWuGK+qhIvK3LnSxOy1/NThR5BOzHMtB1yWZX5xmfFFl0e7Oot8GqkULu7mcFZGlyrSVJQyTfxz5njlDX/KS+2bNfd2yPGeBTj0LSRyDO+mgnASma24zSBNWItatPi9Jau8cmP5xPryQREzNgDhjrenHRRnHxr++cvAPhv5TmLzJebzDPySj7kyRoGcdsFdnyWBzQvGPUuiYvkFDO30R0Xmz5cn3wRPvvqQeLq6kNQEbSbS3uyy5kpzQiEY1KkYahGYjuACQ7DPQbinu3i+rAmzDAEmPJRtpnzNt8vwA0zGeN9MwnwZ4qwSQlPoxyZ1sKKbplaKGmW+jT8v1rkSk/R800Uxpx/xJapoTLLJV09s0p4sLC5wTG7n12zYTu/adNk3I5jQwq/QXqj5URIq3XHu2ZFeEpKYhACl3zGKADE4eiaCvOk8I+mKrTWKVlO1+iCVXUCpWJRBhLQx6snpylQ==
  template:
    metadata:
      name: tinyauth-key
      namespace: auth
