homeAssistantVolumeSizeGi: 5
databaseVolumeSizeGi: 10
mqttVolumeSizeGi: 1
zigbee2mqttVolumeSizeGi: 1
esphomeVolumeSizeGi: 10
zigbeeAdapter: "tcp://192.168.5.6:7638"

images:
  homeAssistant:
    repository: homeassistant/home-assistant
    tag: "2026.5"
    pullPolicy: IfNotPresent
  mqtt:
    repository: eclipse-mosquitto
    tag: 2.0.22
    pullPolicy: IfNotPresent
  zigbee2mqtt:
    repository: ghcr.io/koenkk/zigbee2mqtt
    tag: 2.10.1
    pullPolicy: IfNotPresent
  esphome:
    repository: esphome/esphome
    tag: "2026.4"
    pullPolicy: IfNotPresent
