apiVersion: v1
kind: ConfigMap
metadata:
  name: pocketid-config
  namespace: {{ .Release.Namespace }}
data:
  UI_CONFIG_DISABLED: "false"
  APP_NAME: "Home Cluster"
  APP_URL: "https://pocketid.{{ .Values.domain }}"
  TRUST_PROXY: "true"
  SMTP_HOST: "email-smtp.us-west-2.amazonaws.com"
  SMTP_PORT: "587"
  SMTP_FROM: "justin@dray.be"
  EMAILS_VERIFIED: "true"
  EMAIL_ONE_TIME_ACCESS_AS_ADMIN_ENABLED: "true"
