{{- include "common.ingress" (dict "ctx" . "name" "pocketid" "port" 1411 "type" "traefik-private" "auth" false) }}
---
{{- include "common.ingress" (dict "ctx" . "name" "pocketid" "port" 1411 "type" "traefik-public" "auth" false) }}
