apiVersion: pocketid.aclerici.dev/v1alpha1
kind: PocketIDInstance
metadata:
  name: pocketid
  namespace: {{ .Release.Namespace }}
spec:
  appUrl: "https://pocketid.{{ .Values.domain }}"
  encryptionKey:
    valueFrom:
      secretKeyRef:
        name: pocketid-secrets
        key: ENCRYPTION_KEY
  persistence:
    enabled: true
    existingClaim: pocketid-data
  smtp:
    from: "justin@dray.be"
    host: "email-smtp.us-west-2.amazonaws.com"
    port: 587
    user: AKIASWRXGFVDIZYPWCSL
    password:
      valueFrom:
        secretKeyRef:
          name: pocketid-secrets
          key: SMTP_PASSWORD
    tls: starttls
  ui:
    appName: "Home Cluster"
  userManagement:
    allowUserSignups: "disabled"
    emailsVerified: true
  emailNotifications:
    oneTimeAccessAsAdmin: true
    apiKeyExpiration: true
