apiVersion: cilium.io/v2
kind: CiliumNetworkPolicy
metadata:
  name: pocket-id
  namespace: {{ .Release.Namespace }}
spec:
  enableDefaultDeny:
    ingress: false
    egress: false
  endpointSelector:
    matchLabels:
      app.kubernetes.io/name: pocket-id
  ingress:
    - fromEntities:
        - host
    - fromEndpoints:
        - matchLabels:
            k8s:io.kubernetes.pod.namespace: pomerium
            app.kubernetes.io/name: pomerium
      toPorts:
        - ports:
            - port: "1411"
              protocol: TCP
    - fromEndpoints:
        - matchLabels:
            k8s:io.kubernetes.pod.namespace: {{ .Release.Namespace }}
            app.kubernetes.io/name: pocket-id-operator
      toPorts:
        - ports:
            - port: "1411"
              protocol: TCP
  egress:
    - toFQDNs:
        - matchName: "email-smtp.us-west-2.amazonaws.com"
      toPorts:
        - ports:
            - port: "587"
              protocol: TCP
    - toEntities:
        - world
---
apiVersion: cilium.io/v2
kind: CiliumNetworkPolicy
metadata:
  name: pocket-id-operator
  namespace: {{ .Release.Namespace }}
spec:
  enableDefaultDeny:
    ingress: false
    egress: false
  endpointSelector:
    matchLabels:
      app.kubernetes.io/name: pocket-id-operator
  ingress:
    - fromEntities:
        - host
  egress:
    - toEndpoints:
        - matchLabels:
            k8s:io.kubernetes.pod.namespace: {{ .Release.Namespace }}
            app.kubernetes.io/name: pocket-id
      toPorts:
        - ports:
            - port: "1411"
              protocol: TCP
    - toEntities:
        - host
        - remote-node
