apiVersion: pocketid.internal/v1alpha1
kind: PocketIDOIDCClient
metadata:
  name: testclient2
  namespace: default
spec:
  isPublic: false
  callbackUrls:
    - https://tesc.{{ .Values.domain }}/callback
  logoutCallbackUrls:
    - https://testc.{{ .Values.domain }}/logout
