apiVersion: longhorn.io/v1beta2
kind: Volume
metadata:
  name: pocketid-data
  namespace: longhorn-system
  labels:
    recurring-job-group.longhorn.io/backups-enabled: enabled
    recurring-job-group.longhorn.io/fstrim-enabled: enabled
spec:
  size: "1073741824"  # 1Gi
  dataLocality: best-effort
  numberOfReplicas: 2
  accessMode: rwo
  frontend: blockdev
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pocketid-data
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: longhorn
  csi:
    driver: driver.longhorn.io
    fsType: ext4
    volumeHandle: pocketid-data
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pocketid-data
  namespace: {{ .Release.Namespace }}
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn
  volumeName: pocketid-data
  resources:
    requests:
      storage: 1Gi
