apiVersion: v1
kind: Service
metadata:
  name: theclaw
  namespace: {{ .Release.Namespace }}
  annotations:
    external-dns.alpha.kubernetes.io/hostname: theclaw.{{ .Values.domain }}
    external-dns.alpha.kubernetes.io/target: {{ .Values.network.theclawServer }}
spec:
  ports:
    - protocol: TCP
      port: 18789
      targetPort: 18789
---
apiVersion: v1
kind: Endpoints
metadata:
  name: theclaw
  namespace: {{ .Release.Namespace }}
subsets:
  - addresses:
      - ip: {{ .Values.network.theclawServer }}
    ports:
      - port: 18789
