apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: default
  namespace: {{ .Release.Namespace }}
spec:
  addresses:
    - {{ .Values.network.metallbRange }}
  autoAssign: true
---
apiVersion: metallb.io/v1beta1
kind: L2Advertisement
metadata:
  name: default
  namespace: {{ .Release.Namespace }}
spec:
  ipAddressPools:
    - default
---
apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: public-ingress
  namespace: {{ .Release.Namespace }}
spec:
  addresses:
    - {{ .Values.network.publicIngress }}/32
  autoAssign: false
---
apiVersion: metallb.io/v1beta1
kind: L2Advertisement
metadata:
  name: public-ingress
  namespace: {{ .Release.Namespace }}
spec:
  ipAddressPools:
    - public-ingress
---
apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: dns-server
  namespace: {{ .Release.Namespace }}
spec:
  addresses:
    - {{ .Values.network.dnsServer }}/32
  autoAssign: false
---
apiVersion: metallb.io/v1beta1
kind: L2Advertisement
metadata:
  name: dns-server
  namespace: {{ .Release.Namespace }}
spec:
  ipAddressPools:
    - dns-server
