apiVersion: v2
name: audiobookshelf
description: A self-hosted audiobook and podcast server
type: application
version: 0.1.0
appVersion: "2.33.1"
dependencies:
  - name: common
    version: 0.1.0
    repository: "file://../../common"
