configVolumeSizeGi: 5
metadataVolumeSizeGi: 5

images:
  app:
    repository: ghcr.io/advplyr/audiobookshelf
    tag: 2.33.1
    pullPolicy: IfNotPresent

mediaPaths:
  audiobooks: /mnt/pool/media/audiobooks
  podcasts: /mnt/pool/media/podcasts
