apiVersion: v1
kind: ConfigMap
metadata:
  name: jellyfin-rffmpeg-config
  namespace: {{ .Release.Namespace }}
data:
  rffmpeg.yml: |
    rffmpeg:
      logging:
        log_to_file: true
        datedlogfiles: true
        datedlogdir: "/config/log"
        debug: true
      directories:
        state: "/config/rffmpeg"
        persist: "/run/shm"
      remote:
        user: jellyfin
        persist: 300
        args:
          - "-p"
          - "2222"
          - "-i"
          - "/config/.ssh/id_ed25519"
          - "-o"
          - "StrictHostKeyChecking=no"
          - "-o"
          - "UserKnownHostsFile=/dev/null"
      commands:
        ssh: "/usr/bin/ssh"
        ffmpeg: "/usr/lib/jellyfin-ffmpeg/ffmpeg"
        ffprobe: "/usr/lib/jellyfin-ffmpeg/ffprobe"
        fallback_ffmpeg: "/usr/lib/jellyfin-ffmpeg/ffmpeg"
        fallback_ffprobe: "/usr/lib/jellyfin-ffmpeg/ffprobe"
