apiVersion: v1
kind: ServiceAccount
metadata:
  name: jellyfin
  namespace: {{ .Release.Namespace }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: jellyfin-worker-discovery
  namespace: {{ .Release.Namespace }}
rules:
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["get", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: jellyfin-worker-discovery
  namespace: {{ .Release.Namespace }}
subjects:
  - kind: ServiceAccount
    name: jellyfin
    namespace: {{ .Release.Namespace }}
roleRef:
  kind: Role
  name: jellyfin-worker-discovery
  apiGroup: rbac.authorization.k8s.io
