apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: jellyfin-grpc-worker
  namespace: {{ .Release.Namespace }}
spec:
  encryptedData:
    VALID_TOKEN: AgCefD75hJzTcO51g9iLA0raNkn5QPux/Nph4Clg34KglgU+pA2iY1e9I434oEXeOYonDU8AsfYreLfzhRhROgdx1KNMknDmGOY3zQ2KzjjRs2JklRbXnBjJZAPm1vk5SfZOhlkj0RsBopU6J5jyNKtLe79DOpj+XGv7ph0mZ1sqXO+EC2cFHnY4opWcOW/NJhUOu5v5uMDtTPgLJItGG1HDj7Uj/YXR+hcHZJJIuFkxOHZxiDDHnmCg679wMb/2HlW/uIao+fM11ncwC/14qn4i/hTI9mTUFOHdJLwM4o7FeeF9itkbU35K8HD3xw6QqzJzfw1y4ZQhKtXI4LzP3wgdQY9r1g/9oa0NFXPT01v7HFc5/lBXuAizo9TQyqb4YsHv/uvR9BdjhmwEMQlNcwF7xymhzXcDWY5yWwm6NSK7WdTlvzJbbFrLKuHhoVSpJvMMkDXu503WDvCcVddF2cEMRPEj/FgEbmkI4Vz1yivo/hnNRZShjq2ihgH4ULCoqAnkFioyYplF7oEGWhrC4X99QVeKMXKy/fIr9oqUMH2SG41lt2Mn5ZRbmD1feqQjL5uV+r8t/4XjHwUfHXUDC9xGh57l4SweM+8blVG7OuVchnmN2/j5TRh340i6NLVg70xwZSS8V/7r9FFYoDs6MNs83+z15Fc6U7+DtpUC8gkD6eYtzFvMyip5LgKcIv8B/oi8FuhVYLovbqjnd57dQ7cA4EjTH0zBRp9tJ2VgU5jk7p+TkPUWK47AnVjWxVi//GBJiz7W9YVGSAN3MV3GELrL
  template:
    metadata:
      name: jellyfin-grpc-worker
      namespace: {{ .Release.Namespace }}
