{{- include "common.longhornVolume" (dict "ctx" . "name" "jellyfin-config-v2" "sizeGi" .Values.volumeSizeGi) }}
---
{{- include "common.longhornVolume" (dict "ctx" . "name" "jellyfin-cache-v2" "sizeGi" (.Values.cacheVolumeSizeGi | default 50) "shared" true) }}
