{{- include "common.longhornVolume" (dict "ctx" . "name" "jellyfin-config" "sizeGi" .Values.volumeSizeGi) }}
---
{{- include "common.longhornVolume" (dict "ctx" . "name" "jellyfin-cache" "sizeGi" (.Values.cacheVolumeSizeGi | default 50) "shared" true) }}
