apiVersion: cilium.io/v2
kind: CiliumNetworkPolicy
metadata:
  name: renovate
  namespace: {{ .Release.Namespace }}
spec:
  endpointSelector:
    matchLabels:
      app.kubernetes.io/name: renovate
  ingress: []
  egress:
    - toEntities:
        - world
