---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: renovate-secret
  namespace: renovate
spec:
  encryptedData:
    RENOVATE_TOKEN: AgBfR+2hBezHQTjzG+VfyGOPiOA8JZXm182J5ZiFgAC+8JiZUoYx2Xh2FlcAWWw6hVAf3p6KKXx+bVH4SVGLv7vm19UdZRGKFSPQBqFq4aQrKJO7j0bf3Y8rRbNiOhGmwufrzvw1ZH0vcddCPU0mt8HervTFleLX/MOviFTIZJ0LhVXcDg4hSDbnfb2DRjp1+Wml8+GxccPfRZbeHxXRK3hwjVEai18cBL+IyJvwqDq/PU42VrCnORwLU1gKsD+i0RAAnLuvXAhazIVUE4eMJ9GZa09kOpcNUqzfqORH8Yw7POyNT2gnwwWEWm2zsVdpuqlamS0UGqDJXr6R4cdHd4olO5Mm4XyyKDCkATSNYcX1+tAy6OSkw1XO/DDiCvJ6g+rbJaIBXlXtzmMupSCsTuq4YpGj/RWvuWRZMJLWT630cbpihIuKYXuM7X/uyQ2ZbbmJ4SwtIT5kXjsFlSzDDXFhnlLZfK2ZWtZq44ZNFwpK8NUlEdjuhyLYFuhXcyZT5GikgM+RXmm/sQMdTvUicNKzy7AGN9VoHlsGIZDsLC6LLAgIEMUegeyov4LjBfQ9sMLkifa3Us5JhhcbtqHuppSkDoJwxID7MtWaIHRIm/6jt1Jlp6n/8v5rgDwlbb9p1USA3jrDQdQN/6/SKoJMKHbncKQNWF0bdq213HtDMneqcoJp4Xo7xu/02SsqKNP0l5DccQLcqqLUdF8rIaj0TeZxd6ujErHy3gTjXczZXlFwf4vIbh1Hsqtj
  template:
    metadata:
      name: renovate-secret
      namespace: renovate
