apiVersion: v1
kind: ConfigMap
metadata:
  name: qbittorrent-config
  namespace: {{ .Release.Namespace }}
data:
  TZ: {{ .Values.TZ }}
  PUID: {{ .Values.PUID | quote }}
  PGID: {{ .Values.PGID | quote }}
  TORRENTING_PORT: "9514"
