---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: qbittorrent-vpn
  namespace: downloads
spec:
  encryptedData:
    wg0.conf: AgC4Rp9/MjpafNuArsI5G3stj1qRIcLNUSHeV0+6f7fM2pgLJ+h5FCzt2Lfe+lE+/aycf5IgPUyhnTS95sBeey5H1DkkXmr4xgz6efyLR+ST82XqTjeVOXkduWAWdWXHpPkVV96+8ACz27lMpRYLzmOX/ywNeTkAWLOskT3pOMYk5lyaeRP/+muM3CZeALP3fJVTFIhZ5yV/zcj4O7RE3cFobCUezHhZEPmw1JWtHVJ52gqQC2W1ZDvZwyngcgplXsBtqhx9qhahfpMrpRpiq3lSNhfz9G/9u06rO/pnHqCbgBsK90ZvKgmb0S8CGRiLV+lKVY/5PXBlx8JuRf/T/XqWPXJaUDFQkiLVA0O8LM+nfH8vkLo9JsAqyofvG53SJdfjWSSKQpWGOcc/W5ZpXjA8QDV8TK+NXz4V3nybI30Kc+yQvPOiOvD9RST/NEEzGG+fcD/X2Im6maKQQWIJOdhOJ5bb5LS5OqCGzq3gcqxnM+IyUcY81oT1SMFhvL+jzhfB6oXGev/9l4xn/N54H+Ya7Vqc4blHXYdJs2jSbEmRwkHpQjz5qcFz6svA4TxQglGjZP+v1AyqShd81Z9m047NDodskkyPMPMB1imjqnsOo2n3t5ygQeE9ZQeNILPQApuNcT+6xlRFUvBqwT8D8ySsKfNCCAkrtSarnoSYzmIlLK7+5X//L743GpmWECvX7s231sanmLTxgDXt4XL/K9bumlZ2rKyZM2uNC5loVNa7U9k549WLPOc0lCKCBpVyL+U2yLKhuOnNoiRC/xs28NIpRG51HiuBeZ7g+2U2mDJ0LgMsGML3E4mmgKq/2H3KfCCN+s7G+PwIi0Rt8RPozcO0JFbRczZz8uJbxz2O/XsLJHA8WRVssaH0yPGegtge2SwlVTXXgOehojygbwkEhv6Q5ltECinj9bz3Y1fYeGYtO3gw0qG4kj4Q97nvrRQ/2lDxqSGcH5DhIgRfVYnjrRAKPSFqWoc0LjOqzeggLYkO59aBgp0ipi5uD/eNz1Tar+GCxzcfeft4koPt9C1j9Qo7pRPAOpOAwvT6HUH5mqHmmPNssbXWBZQJgynLQkUoF5R/hcbqVcYy5fhMiPh7U7VtRfoaFT2F2kOa/5aj36tZ5qCL/h/lAe36pIehziBeZQ3BDQmjJxVBrlGdGX3WzgwMMZtBeaGr4Y7guCBpnVD8wiaqASS2N4AUWAEvEaQLsxAGuXWRWDWUUYSdSFJFJdWtPaUIxdNLow==
  template:
    metadata:
      name: qbittorrent-vpn
      namespace: downloads
