---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: qbittorrent-vpn
  namespace: downloads
spec:
  encryptedData:
    wg0.conf: AgC4z/bqE21TCXZ/SlGMrf305msF0qj/CAggN+8k/LOD5WO9eKBsV3I/zHkpahVFAtgqSpZiliCEimI2hcGLbdEzzAbEjTYl6dtEh4fnt0YKZ2pqXkwY+PM4065a0JEMQ+kHQb+O0kZadkoVKQnFpxs2Znnxo5LKDgpk2UPbuBNcCgP5o6hIaAWkEj6Wue4OELDp/Z75CkVOMLhJTL/VHkh8yz4XjTiBhrhnrrI/MN7zDP/djWCCSWuxc23IvIa3VVhUjjWiFhNys/IdCepCeTJK6YQr9trbbDOdL+zqjMQih5rJaBl4hbpQDITO9v6sYPEZGkaUwQd3LaJ1DL8/fmTCSTn1QHwrNi/Cd+n/zTGc4ahsm/houaBDmQdpMuEYWQ2CBSedf6kSgiVbse6IHlq8rGD7jYvNk1rRworeazuMT3hkLOaiUscikXhEUMvLyoFipP0qe0Nbzcq9uirhg5+dfN3WcjdeSCzLPBbhR7v1+eyExEqwEmW63IIfkvQC6keKYstDkRq5NgG2PWWRYa0+BOgOoIxcJJODjKcd1/4TCOoQq8ZPOnkd9OgA0+JUxfvH9/YRmEfI23GlXWULyRWqTKeFKPx4w6aNG9+u5IDuANB+MXrMympZOEPSH84HBhPJS6Bau3J+du7bObJ4PhCRZpZ6hbGMVKHHAQBpOJEt18ESvpwfD3ne9u/EhsxJydlAhguqOO25U4sGB3y46GeK35Lic955PxENCShdIHcdZ2heVA3Vet/bDpbqtPY4giSZx5LAJ6Y4MyLLGW0fTfM5h47z+z49bk6UfnuXPALHxgwAEG+aVhWKEif+vCZUt5pZbjtHNWXfEGM/yveAdXSmWNtFAqW8XVkZcrJ78DdQjBZxnJYOnrJ4RN2dqwBuTN1TX45u3VLCGS7zFHmCjhbwWM9G3+jyKntch94ApwvGulwji5N2T9oQ8kBK1A56gg79P7Cpg+tYRWkfuOy4gDRtxltcvyaHsSyBMPJ6YfyEVB09Y9idfa21L639NOLxpew3kQcj56zvaarrK1H658R6UzktWV02Uoe/LJpC1pvLP15Eqs4IqsVdEE0TizuD6+B4eEtUmDDzmd8KtNgajP9klTu2p6izoMixC7I+n/AzlPmaj6CxhEeONITklbZvKgd9dIQ2yLIbWrRkwtfVdQr5EkS4BUjyUGyKnq4kOeqChfRwdOhfB7UKnGuGPxv4xrzhw4W30raZMKhGNMuCV+ykFKVvyBXUDxo=
  template:
    metadata:
      name: qbittorrent-vpn
      namespace: downloads
