apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: wildcard-cert
  namespace: {{ .Release.Namespace }}
spec:
  secretName: default-tls
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  commonName: "*.{{ .Values.domain }}"
  dnsNames:
    - "*.{{ .Values.domain }}"
  secretTemplate:
    annotations:
      reflector.v1.k8s.emberstack.com/reflection-allowed: "true"
      reflector.v1.k8s.emberstack.com/reflection-allowed-namespaces: "kube-system,shared-secrets,cert-manager,traefik-private,traefik-public,pomerium"
      reflector.v1.k8s.emberstack.com/reflection-auto-enabled: "true"
      reflector.v1.k8s.emberstack.com/reflection-auto-namespaces: "kube-system,shared-secrets,cert-manager,traefik-private,traefik-public,pomerium"
