{{ include "common.pomeriumIngress" (dict
  "ctx" .
  "name" "radarr"
  "port" 7878
) }}
---
{{ include "common.pomeriumIngress" (dict
  "ctx" .
  "name" "radarr-api"
  "subdomain" "radarr"
  "port" 7878
  "path" "/api"
  "allowedUsers" "all"
) }}
