{{- include "common.ingress" (dict "ctx" . "name" "radarr" "type" "traefik-private" "port" 7878 "auth" true) }}
---
{{- include "common.ingress" (dict "ctx" . "name" "radarr" "type" "traefik-private" "port" 7878 "auth" false "path" "/api") }}