{{- range (list "decluttarr" "prowlarr" "qbittorrent" "radarr" "sabnzbd" "seerr" "shelfmark" "sonarr") }}
---
apiVersion: autoscaling.k8s.io/v1
kind: VerticalPodAutoscaler
metadata:
  name: {{ . }}
  namespace: {{ $.Release.Namespace }}
spec:
  targetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ . }}
  updatePolicy:
    updateMode: "InPlaceOrRecreate"
    minReplicas: 1
{{- end }}
