apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: immich-database-old
  namespace: {{ .Release.Namespace }}
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn
  volumeName: immich-database-data
  resources:
    requests:
      storage: {{ .Values.databaseVolumeSizeGi }}Gi
---
apiVersion: batch/v1
kind: Job
metadata:
  name: migrate-immich-data
  namespace: {{ .Release.Namespace }}
spec:
  template:
    spec:
      containers:
      - name: migrate
        image: alpine
        command: 
          - "/bin/sh"
          - "-c"
          - |
            echo "Starting migration..."
            # Copy to database-1
            rm -rf /new1/pgdata/*
            cp -a /old/pgdata/* /new1/pgdata/
            echo "Instance 1 complete."
            # Copy to database-2
            rm -rf /new2/pgdata/*
            cp -a /old/pgdata/* /new2/pgdata/
            echo "Instance 2 complete."
            echo "Migration finished successfully."
        volumeMounts:
        - name: old-vol
          mountPath: /old
        - name: new-vol-1
          mountPath: /new1
        - name: new-vol-2
          mountPath: /new2
      volumes:
      - name: old-vol
        persistentVolumeClaim:
          claimName: immich-database-old
      - name: new-vol-1
        persistentVolumeClaim:
          claimName: immich-database-1
      - name: new-vol-2
        persistentVolumeClaim:
          claimName: immich-database-2
      restartPolicy: Never
  backoffLimit: 0
