apiVersion: postgresql.cnpg.io/v1
kind: ScheduledBackup
metadata:
  name: immich-database-daily-backup
  namespace: {{ .Release.Namespace }}
spec:
  schedule: "0 0 2 * * *"
  backupOwnerReference: self
  cluster:
    name: immich-database
