apiVersion: longhorn.io/v1beta2
kind: Volume
metadata:
  name: immich-database-data
  namespace: longhorn-system
  labels:
    recurring-job-group.longhorn.io/backups-enabled: enabled
    recurring-job-group.longhorn.io/fstrim-enabled: enabled
spec:
  size: {{ mul .Values.databaseVolumeSizeGi 1024 | mul 1024 | mul 1024 | quote }}
  dataLocality: best-effort
  numberOfReplicas: 2
  accessMode: rwo
  frontend: blockdev
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: immich-database-data
spec:
  capacity:
    storage: {{ .Values.databaseVolumeSizeGi }}Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: longhorn
  csi:
    driver: driver.longhorn.io
    fsType: ext4
    volumeHandle: immich-database-data
