---
# tasks for mdns role
- name: Install mDNS/Avahi package
  ansible.builtin.package:
    name: avahi
    state: present
  tags:
    - mdns

- name: Ensure avahi-daemon is started and enabled
  ansible.builtin.service:
    name: avahi-daemon
    state: started
    enabled: true
  tags:
    - mdns

- name: Ensure mDNS is enabled in /etc/systemd/resolved.conf
  ansible.builtin.blockinfile:
    path: /etc/systemd/resolved.conf
    create: true
    block: |
      [Resolve]
      MulticastDNS=yes
    marker: "# {mark} ANSIBLE MANAGED BLOCK: mDNS configuration"
    backup: true
    mode: 644
  notify: Restart systemd-resolved
  tags:
    - mdns

- name: Ensure nsswitch.conf uses mdns for hosts
  ansible.builtin.lineinfile:
    path: /etc/nsswitch.conf
    regexp: "^hosts:"
    line: "hosts: files mdns_minimal [NOTFOUND=return] resolve [!UNAVAIL=return] dns mdns myhostname"
    backup: true
  tags:
    - mdns
