volumeSizeGi: 50
cacheVolumeSizeGi: 50

worker:
  replicas: 3

images:
  app:
    repository: ghcr.io/justin8/jellyfin-rffmpeg
    tag: "12.1"
    pullPolicy: Always
  worker:
    repository: ghcr.io/justin8/jellyfin-rffmpeg-worker
    tag: "12.1"
    pullPolicy: Always

theme:
  abyss:
    enabled: true
    repo: "AumGupta/abyss-jellyfin"
    branch: "main"
    autoDefaults: true
