argo-cd:
  dex:
    enabled: false
  notifications:
    enabled: false
  applicationSet:
    enabled: false
  configs:
    cm:
      users.anonymous.enabled: "true"
    rbac:
      policy.default: role:admin
    secret:
      githubSecret: "$argocd-webhook-secret:webhook.github.secret"
      extra:
        server.secretkey: "$argocd-server-secret:server.secretkey"
  server:
    extraArgs:
      - --insecure
