argo-cd:
  dex:
    enabled: false
  notifications:
    enabled: false
  applicationSet:
    enabled: false
  configs:
    cm:
      users.anonymous.enabled: "true"
    rbac:
      policy.default: role:admin
  server:
    extraArgs:
      - --insecure
  controller:
    clusterRoleRules:
      enabled: true
      rules:
        - apiGroups: ["rbac.authorization.k8s.io"]
          resources: ["rolebindings", "roles"]
          verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
