apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: immich
  namespace: {{ .Release.Namespace }}
  annotations:
    ingress.pomerium.io/allow_public_unauthenticated_access: "true"
    dns.external/enabled: "true"
    dns.external/target: home.{{ .Values.domain }}
spec:
  ingressClassName: pomerium
  rules:
  - host: immich.{{ .Values.domain }}
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: immich
            port:
              number: 2283
