{{- range list "traefik-public" "traefik-private" }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: immich{{ if eq . "traefik-public" }}-public{{ end }}
  namespace: {{ $.Release.Namespace }}
  {{- if eq . "traefik-public" }}
  annotations:
    external-dns.alpha.kubernetes.io/target: home.{{ $.Values.domain }}
  {{- end }}
spec:
  ingressClassName: {{ . }}
  rules:
    - host: immich.{{ $.Values.domain }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: immich
                port:
                  number: 2283
  tls:
    - hosts:
        - immich.{{ $.Values.domain }}
      secretName: default-tls
---
{{- end }}
