apiVersion: v1
kind: Service
metadata:
  name: immich
  namespace: {{ .Release.Namespace }}
  annotations:
    netbird.io/expose: "true"
spec:
  selector:
    app: immich
  ports:
    - port: 2283
      targetPort: 2283
