apiVersion: apps/v1
kind: Deployment
metadata:
  name: grist
  namespace: {{ .Release.Namespace }}
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: grist
  template:
    metadata:
      labels:
        app: grist
    spec:
      containers:
        - name: grist
          image: gristlabs/grist:1.7.11
          ports:
            - containerPort: 8484
          envFrom:
            - configMapRef:
                name: grist-config
            - secretRef:
                name: grist-secrets
          volumeMounts:
            - name: persist
              mountPath: /persist
      volumes:
        - name: persist
          persistentVolumeClaim:
            claimName: grist-persist
