apiVersion: apps/v1
kind: Deployment
metadata:
  name: grist
  namespace: {{ .Release.Namespace }}
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: grist
  template:
    metadata:
      labels:
        app: grist
    spec:
      containers:
        - name: grist
          image: "{{ .Values.images.grist.repository }}:{{ .Values.images.grist.tag }}"
          imagePullPolicy: {{ .Values.images.grist.pullPolicy }}
          ports:
            - containerPort: 8484
          envFrom:
            - configMapRef:
                name: grist-config
            - secretRef:
                name: grist-secrets
          env:
            - name: GRIST_OIDC_IDP_CLIENT_ID
              valueFrom:
                secretKeyRef:
                  name: grist-oidc-credentials
                  key: client_id
            - name: GRIST_OIDC_IDP_CLIENT_SECRET
              valueFrom:
                secretKeyRef:
                  name: grist-oidc-credentials
                  key: client_secret
          volumeMounts:
            - name: persist
              mountPath: /persist
      volumes:
        - name: persist
          persistentVolumeClaim:
            claimName: grist-persist
