{{- range list "traefik-public" "traefik-private" }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: grist{{ if eq . "traefik-public" }}-public{{ end }}
  {{- if eq . "traefik-public" }}
  annotations:
    external-dns.alpha.kubernetes.io/target: home.{{ $.Values.domain }}
  {{- end }}
  namespace: {{ $.Release.Namespace }}
  annotations:
    traefik.ingress.kubernetes.io/router.middlewares: {{ . }}-tinyauth@kubernetescrd
spec:
  ingressClassName: {{ . }}
  rules:
    - host: grist.{{ $.Values.domain }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: grist
                port:
                  number: 8484
  tls:
    - hosts:
        - grist.{{ $.Values.domain }}
      secretName: default-tls
---
{{- end }}
