apiVersion: pocketid.internal/v1alpha1
kind: PocketIDOIDCClient
metadata:
  name: grist
  namespace: {{ .Release.Namespace }}
spec:
  name: Grist
  isPublic: false
  callbackUrls:
    - https://grist.{{ .Values.domain }}/oauth2/callback
