apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: teslamate-secrets
  namespace: teslamate
spec:
  encryptedData:
    ENCRYPTION_KEY: AgAqOcC9SSAXiO/etyaNYssqHPkj9oaY2FEVLGMhJOpMRkdC1V4Q/nQzlG/MvXETj+BmSiXFNOZu2Zm0M/5vzMss3sQJq6WCq2NbssZLNhBS9EcY7y7Zq4jm5YCjMbXBPci5719sqt37E1Ab3tIAbijP5TrXBZo9hV0b6BmjN2dUBm70KZJe8g4GUHXYHV74ahkR7nr3CL4DjNNIHHKGsVxAPMbf9LutZmN48oEkkiMnGmoga9GZGSP5l1aCuj7PAMJGEVAjm8lV/sLFINN9bamzdgqpcb4wDmGuwd0OYwOEU32rrgX7Iz4yMcA7RrjlbjOKGmqbdcipZt6XZbGohsakoAO2dGHBn8Q1l0UhCbcmMhZ5GjdGcjIsBTUWN/QCFsdKuzx26hvKhHgDW8S+1Tfj65yN8/DE9QEmdTZiZGOy95qoTiep1Sr8g3G4yWSC2LDJPJL5xl+00K35AkYFzvSEuJt2nLa1v2Og8N0QN2IWGHN2ACyDFBiilYUbQqjPYiZCzxKg4yoLbwTXslHnBB9/TTUO/mIKtVrNKfAkc5dCKthfKda5yIx+NZl577OE73mKq4Lp/2l/jj9hf+e6mXfwQU4HevIMhR2a7zr2pRzD4dMw+Zi9Dq1cGaU2b9M011OZL/SaLV/jwTrNKDrQPX7YYXvjuSV9/l2QJ9b22xWoU84xV/LIXyXnDnNObm7Gu7rAue9wU/NSuy/l/oG3qcRjN1WJiMPMfkHpK+EZhYJIuZjcky0YiY+l4Q34qw==
  template:
    metadata:
      name: teslamate-secrets
      namespace: teslamate
