renovate:
  renovate:
    configIsJavaScript: true
    config: |
      module.exports = {
        platform: 'github',
        autodiscover: true,
        autodiscoverFilter: [
          'justin8/*',
        ],
        onboarding: false,
        hostRules: [
          {
            matchHost: 'ghcr.io',
            hostType: 'docker',
            username: 'justin8',
            password: process.env.RENOVATE_TOKEN,
          },
        ],
      };
  cronjob:
    schedule: "0 * * * *"
    concurrencyPolicy: "Forbid"
    failedJobsHistoryLimit: 3
    successfulJobsHistoryLimit: 1
    jobRestartPolicy: "Never"
  existingSecret: "renovate-secret"
  resources:
    requests:
      cpu: 100m
      memory: 512Mi
    limits:
      memory: 2Gi
