apiVersion: tailscale.com/v1alpha1
kind: Connector
metadata:
  name: home-exit-node
  namespace: tailscale
spec:
  replicas: 1
  hostnamePrefix: home-exit-node
  subnetRouter:
    advertiseRoutes:
      - "192.168.5.0/24"
