---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: operator-oauth
  namespace: tailscale
spec:
  encryptedData:
    client_id: AgAssC67q3gkTaLg9HbcSI703CFVZ1HsXDcVuwqzfwmtzYY8pg+3r+8UHPwHobbzjRF8nHUH4srrzRJotTgzw+wVRirBYCTLIsOcqyXiq0jpYN52pwwb2AWl9/1UXNPMBEh9Nc0NSwbPA8DED/AGb9hw3iGOTNuAEhUkisr0W5AhtG4biHmus2ZbKXPmodDInn6sEs7UerYBfmmn1Y7dNijHhb586Dd23boi3dGoZvfRqcM6G0xTohA0xalax97gBw7+92MAKxqEqHntUd4tQmgbqMac8hB+97jQoV2UPvBgJj/pIW+nJ4XQtgi4teOt8G+Fj6PSEHmQdSVDohXOeikOWwBMF/qlzewpzJXSs6O+Y4U5EiTKcYYe8F5zxICSDJcCG+wXTtQedRAGpFc3HxKaYHWtrjDTmNTeLDcDDLYYs7+Ac+fxGiCnXjPWMVXLtmKJq5CfCUtWLTpq1Vj0B0aODaBbroYNBfzolH1zSmkI5uZVUxVGnvuuev/gzS4yxgFoQe5vJuatSXNmWRpSVG3Exp2rCgPZfFkNq9R4s6HA5EcduPnG/K4yr9bDQ+bt1g39vkiXqkH1Liq5EJ2Zap//vvXtSH62gsB3yDl+54ERHgEy7DpXZrN5SPcgKPb8C6AbtTwWjuaoqsWjuI2BzAg/Ed6rTI6z8dvGxwr90FIqBA5knarCGt1FxiUioC5YdM7Z8y+LE0mgh2IaICpfRwTZ8Q==
    client_secret: AgC+1Y/lfw9Zp5ZDIRie/KoeTnrhpYzLsc+IwFMDgy/ZR2F4ySR7938p+aUVWN5XN/6VdQ59GQp2wMhrRjGiPzsu+fSKsqeh6EYjMnxYb/p2JLivDn01JpRkniaj/rFB6nMZrEruU2U8Z68Zh0srvgo7zvXVLQknvzDbDpFRUrmavsgpw0UAAI1W+nDOxfz+nVnSpefMDmhZknBnwk2hk9usxUa8QwR1jENv0l3dt86HzboJtiKAwDPe/whm+NuTpwaXM4YTPYOy0RgjT8gP967QhqsTU1BdH60OUzgju/oSCVpT8lF19SSFhA+tEAoqVaaSjGyd09XYFh21tD+wu55sLArNKencBSKPUADdbzr0qvViLXsKY0ii9ByPKhZOxqxRQaWpI2eBmzUg4aU7rsIDSKXKZRY0T1vsEU2K2o2eUxmAP6otxtcyvNXeDw+oMks9aYv0iiCXJy31QUkt0pbMmM7z4RaKTSsk2h4kd3oQkDB+Okpr8zI91ehhSfbcM0/AabhJ1YTOWBxEB0jSfjyIiBhRemMrajDavM6LY8+G/133Ts2qZ/Yor/i7cOLIfsxW2m+C24yGgJwuc9DwMTzdW9VD9I58MTI8VYWPsWM714qvFoB2MhTU51zeNFKQeEQJ4Kkq5Gptpj4mOBCQFnV5PaTM0UA7mgmHl7J9ILTJEtWe5GljULQI4ZB+IbDE7euEmyU4823XhYK1La2WqSnXevYY39HUpHekUWqyVWcSNlinJGh/bVA1Z7CMuXfuZcr957RsZvDqGCWEu8LYJMQ=
  template:
    metadata:
      name: operator-oauth
      namespace: tailscale
