secret_ssh_authorized_keys:
    - ENC[AES256_GCM,data:TC0sNuefnI1GOueT9jGs4wfzdmK+oDj4nJ4b+J6I2jfUi4MpedqlygBFin5kgFqbNHsjQy9Qpnw58KzyWPVufhRU1hVYeRw7+f6FP8mmTrUprVrDtTnZ82z34R35Rd0SP2BOesFeF2W34g2evSLEFKlfLZM0ch9WawcvlD8JI63ZoyhOWjGe2fxsOm/1jCXqxwFHeJc43slubPlkB7eG66N+bMxdMyIy2ZP8cBU=,iv:qo/rrhK7D1Nf7fRbE1OhBskhf1PFmc2OmXgCV70a7jU=,tag:EaV4Qn9WGMfPlbSD1yDytA==,type:str]
    - ENC[AES256_GCM,data:kn8uWgDMrNdvtQYcXknQNdCqbaLF/ZDpSv9P49wXne392mGaRwLgJfPtp7OSUTNWMkjHmLsDMrxz1kwm0OIH4SS70HSbT5GyEgqIqeAYaA2V/39E4RCI1nlrbPikLuwPdvj+NmVr5YMMGbc987EvRDIAh27v8QflRf39GEudb7wNrsQlrA/qN1i1s+nyB1EpvO1cH7o7+abtBOq9vKqjPk64QToe7KBAHaR58YQb,iv:7UvbNeqXyli8WkoX9PlDwtYcW8O7/dPFfSXmp0kANv0=,tag:GBpJkF+z1yorn5DhZ29uPw==,type:str]
    - ENC[AES256_GCM,data:OVXw6o0gSXpryMc0VptIp0qhfoCx8fMTiRqWZEkIhRK6AH1AoKIBq102exaE+QA2qZw4WNFway5PLkXeFZy5BaFC5vIKD3Y9Lxdu/gthr0916A2j4NAseE3DDFBh0OpsAa8cIcaX8ugn7adR5gXOTf85nFoSCuL4kEHdLDFwBDRlRlfyzdQKxbz2KIFjKiOQ4XY16GC3GHWivBkkJa1bor6r8FhwdqAoB9V31kxWVMiRMDX+oMWrAo8JdhU=,iv:IcC0U+OYRn7/SoP+QSaHvGvkIoqf3S7d+1HqdGGX07A=,tag:amw3WV/dN2lpGOEpgUvKaQ==,type:str]
    - ENC[AES256_GCM,data:tFcHEc66VxNxbQmp3eP0ns/c3UAEqqEq9e1aydV41wXn78x9AFmqnaHknPIR5VU6DMUl/vf8RYAnO4IcHHt/+BZdK/8BtojevZdsCOLLZziK7UI5ErHRBH8Tctsi,iv:eNGjPYSvL/fSBZEY7TiH0H2gm0u70qdd8F3/3i0GCVg=,tag:vN8FqVs0whoTnaytQfKC4Q==,type:str]
secret_backup_encryption_passphrase: ENC[AES256_GCM,data:lEiNvk7qmMN06LM=,iv:nKAuXOIombiDZBkXLeRo1qRjp0Hdb+43RQx+ss5gRQs=,tag:+vxNKPLwtud06qcUnop2Mg==,type:str]
secret_backup_repository_host: ENC[AES256_GCM,data:Zuo/JixNBtmb2qWjlB2o6oL0,iv:oSyBv1DtxrB70DjHTRqD9yjD1Wg/L5wks2Nm2hrpiqE=,tag:L2ahpUsL2K2NaOm8G//JEw==,type:str]
secret_backup_repository_username: ENC[AES256_GCM,data:jFlsJ5IbCw==,iv:4mieZQfE/xc65FMSFn3LNhNfC3N8b4w7zM46dc9NVPs=,tag:XgzxUG7dbwLKTOCVExK4rA==,type:str]
secret_backup_repository_password: ENC[AES256_GCM,data:RCmeoM+NC/0KREA=,iv:HGMRbrEP4mzxyCzA1UNKLe+1koI3KbmQbfL7dk6s8FM=,tag:cX+X4fFZ07H2PPpwqrIKCg==,type:str]
backup_repository_port: 23
users:
    - name: downloads
      password: ENC[AES256_GCM,data:8tTsbtiy75Z/fuo=,iv:bnAKGJGnWagqmVNCovjuXnskuntQzUeDq92bC14LWbw=,tag:81ltxt3wLrbv0iz3ruZIOA==,type:str]
      uid: 2000
    - name: justin
      uid: 1000
      password: ENC[AES256_GCM,data:8tTsbtiy75Z/fuo=,iv:bnAKGJGnWagqmVNCovjuXnskuntQzUeDq92bC14LWbw=,tag:81ltxt3wLrbv0iz3ruZIOA==,type:str]
      groups:
        - downloads
        - wheel
    - name: celeste
      uid: 1001
      password: ENC[AES256_GCM,data:qIvotTiOyYVjdMc=,iv:rEiCC5Mbmr/0Oc0Rv8IBarrLP8fQmnKbSdTuHMheQgk=,tag:w3IUKY3B6V1olWQIizRcow==,type:str]
      groups:
        - downloads
smtp:
    from: '{{ ansible_hostname }}@dray.id.au'
    username: ENC[AES256_GCM,data:3YyCcxiIKt3GvURyySDunI2VrHY=,iv:1SbUg2UaZod3O54SrlP9ok4zCVez2SdAS7CIcXt+4A0=,tag:RfJIicxOHjD3EJT9tR9MLw==,type:str]
    password: ENC[AES256_GCM,data:8jnWRsPyPR64hw3J6KitFUB7KoPXV8L+nwynjsaeUPb/4K9WHbJZVzFLMKc=,iv:mzE6llAzvdFCDEzyUYl6dCF/u2iiUXpIeW2Akokpky4=,tag:e8fnoCofiTXqVHdj6Fw6rA==,type:str]
    server: email-smtp.ap-southeast-2.amazonaws.com
    port: 587
dns_hosts:
    - ip: 192.168.4.1
      aliases:
        - cerberus.dray.id.au
    - ip: 192.168.4.10
      aliases:
        - home-assistant-au.dray.id.au
        - mqtt.dray.id.au
    - ip: 192.168.4.15
      aliases:
        - rhea.dray.id.au
    - ip: 192.168.4.16
      aliases:
        - storage.dray.id.au
    - ip: 192.168.4.20
      aliases:
        - hestia.dray.id.au
    - ip: 192.168.4.71
      aliases:
        - immich.dray.id.au
        - plex.dray.id.au
        - jellyfin.dray.id.au
        - tinyauth.dray.id.au
        - pocketid.dray.id.au
    - ip: 192.168.4.25
      aliases:
        - leto.dray.id.au
sops:
    age:
        - recipient: age1me7as6xhtzy8eqsqlxgf0v6eq692nstv69eg3hjfrksksm4cm9wspmspwz
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBqcmFRemorbGIweE5RZkFk
            MUVqRVpYTzI5NHJYd1lhNnBUZVFsNXdNeWhrClR5RXB2czRuVlNLcUxPUG02Rklq
            RHRJNndWbUd5NGhLV1d2cENLejc1Yk0KLS0tIE5JU1l1aktSYXRTaktBRHVXV3pK
            QVlOeEhkVk9sVC81YmZLMlkvME4zTFEKhlOq1e4TESdLSZtm4YRMMtlVm3Kfirbh
            Sdwuzuh3V4Yw0RwzfXQ93bI0uuBr09DQcVTWZky3J646lpXC+5OCjw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-08-19T07:48:28Z"
    mac: ENC[AES256_GCM,data:BtrlGrcMmjfWsfBfJNlirihK0xhTRZmxl3aKcx23evlRZlrdyyKx/Qy6qt++v+OMM0PEfvOA86QCLrZW9Doxh6ZyLC0pW4ePFJLu/xf67yiv36Si1novLQ3/E37N3+kLUyNjqhgrbAvwc084wQjw1EFnUiElEhq+VNY5iqCqnvA=,iv:KF/hMO+IO4NjMgd5KItY1LjqBqDR82YOUcFETGKFWwY=,tag:n8PxmeZnpQgXowH2aisFrw==,type:str]
    encrypted_regex: (secret|token|key|passphrase|password|username|url)
    version: 3.10.2
