aws_region: ap-southeast-2

# Global Ansible variables for all hosts
ssh_authorized_keys:
  - ecdsa-sha2-nistp256 AAAAE2VjZHNhLXNoYTItbmlzdHAyNTYAAAAIbmlzdHAyNTYAAABBBF88ymIneFCORv9MOMjHDWD5dswKXM/nbRNtuUP3uS0Icu0ROvWKjP6JWow2PCERWx6YVQV7adzzqUhI1K18W8Q= justin@hades
  - ecdsa-sha2-nistp256 AAAAE2VjZHNhLXNoYTItbmlzdHAyNTYAAAAIbmlzdHAyNTYAAABBBDVritj4bQDwofH/hgzNmYjOAjufpgL4K28n+ppRu77ylDHAl8Jb6/hN/qC+wGR64a34r0csFaxTzXmrO+0djxs= justin@hestia
  - ecdsa-sha2-nistp256 AAAAE2VjZHNhLXNoYTItbmlzdHAyNTYAAAAIbmlzdHAyNTYAAABBBMFBv5hR9yKLqpZ815Vn+iGDAxW7Zk3Iwg5VTsw3A10hC5+fYNaZUjFi8FxcaQfqYyuFmtBsIxMa1e7gADSIJC0= justindray@hephaestus

users:
  - name: justin
    uid: 1000
    password: "{{ lookup('amazon.aws.ssm_parameter', '/home-cluster/users/justin/password') }}"
  - name: celeste
    uid: 1001
    password: "{{ lookup('amazon.aws.ssm_parameter', '/home-cluster/users/celeste/password') }}"
  - name: downloads
    password: "{{ lookup('amazon.aws.ssm_parameter', '/home-cluster/users/downloads/password') }}"
    uid: 2000
