backup_source_directories:
    - /etc
    - /apps/.snapshots/backup
backup_healthcheck_url: ENC[AES256_GCM,data:JiTUVvCZEYb5c//RPrw43F8IXBs/rPkfVkggOYskRy8UPR7Oi2bOa1VuCrkNPW0QjQ7jS0gS9XE=,iv:WMxDtvDexEDSMKnlfW+uWneAH7bsyd+pMtDP/7c0HX4=,tag:66T2wdJ6og0mSoh/Rcek+A==,type:str]
backup_before_commands:
    - btrfs subvolume delete /apps/.snapshots/backup || true
    - btrfs subvolume snapshot /apps /apps/.snapshots/backup
backup_after_commands:
    - btrfs subvolume delete /apps/.snapshots/backup || true
sops:
    age:
        - recipient: age1me7as6xhtzy8eqsqlxgf0v6eq692nstv69eg3hjfrksksm4cm9wspmspwz
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBUZy95V1JKVkc0WnhWODVK
            cDlvZkRKeEUxckQyY2g0UXAybWZPdWlOQlFjCklWK1Z2LzA0M0J6NVUzZVp2a0po
            WUk2MlBjMXNuaDk0VENWM2Zpd1NYb0EKLS0tIDVFNERDMjlFTjNjZklvKy9YNStB
            VWduYnF0aGpvODZDaWk5RWhpdVhWcHcKbwnElIyMUylj7tTzXR49ZM6Zi3bV13l4
            pd/jcNZMwWlIxzHTYGootu1ddYzTF+y9GgeQQKAU0F4Ac21VA7d9wA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-07-24T11:20:47Z"
    mac: ENC[AES256_GCM,data:m4D1IPkTti9pBIOuDY6WlTtoELcPf6f4sh4TtccVJ/XEKNPR3dRBCQS8e9sOUZvafxFTgsuLxAR3VqMvPDk6THINpmnVuiX3zrqgAusbvQftqMWprzOkKcVb0fciMq42G3MC/s4P1RCo9oA476q/6rJmZ18P9hF9WAO9rx6Iflw=,iv:7I445LcfXkg/gHWqZRN7+ag53xxu1gYB3dtXp1oqEQA=,tag:sX/YO6IHB6TBZn7XqMnnHw==,type:str]
    encrypted_regex: (secret|token|key|passphrase|password|username|url)
    version: 3.10.2
