# Samba shares for storage.dray.id.au
smb_shares:
  - name: Backups
    path: /storage/backups
    valid_users: [justin, celeste]
    nfs_exports:
      - hestia.dray.id.au
  - name: Console
    path: /storage/console
    write_list: [justin, celeste]
  - name: Manga-Comics
    path: /storage/manga-comics
    write_list: [justin, celeste]
  - name: Books
    path: /storage/books
    write_list: [justin, celeste]
  - name: Movies
    path: /storage/movies
    write_list: [justin, celeste]
  - name: OSes
    path: /storage/OSes
    write_list: [justin, celeste]
  - name: TV
    path: /storage/tv
    write_list: [justin, celeste]
  - name: Photos
    path: /storage/photos
    write_list: [justin, celeste]
  - name: Downloads
    path: /storage/downloads
    write_list: [justin, celeste]
  - name: Games
    path: /storage/games
    write_list: [justin, celeste]

nfs_exports:
  - name: "hestia.dray.id.au"
    path: /storage
    nfs_options: rw,no_root_squash

disk_encryption_key: "{{ lookup('amazon.aws.ssm_parameter', '/home-cluster/storage/encryptionkey') }}"
