---
- name: Disable SELinux
  ansible.posix.selinux:
    state: disabled
  tags:
    - selinux
    - samba

- name: Include disks, SnapRAID, and mergerfs tasks
  ansible.builtin.import_tasks: disks.yml

- name: Include Samba server tasks
  ansible.builtin.import_tasks: samba.yml

- name: Include NFS server tasks (placeholder)
  ansible.builtin.import_tasks: nfs.yml

- name: Include monitoring tasks
  ansible.builtin.import_tasks: monitoring.yml
