---
- name: Install smartmontools
  ansible.builtin.package:
    name: smartmontools
    state: present
  tags:
    - monitoring

- name: Ensure smartd systemd override directory exists
  ansible.builtin.file:
    path: /etc/systemd/system/smartd.service.d
    state: directory
    owner: root
    group: root
    mode: '0755'
  tags:
    - monitoring

- name: Override smartd systemd unit to disable ConditionVirtualization
  ansible.builtin.template:
    src: smartd.service.override.j2
    dest: /etc/systemd/system/smartd.service.d/override.conf
    owner: root
    group: root
    mode: '0644'
  notify: Reload systemd
  tags:
    - monitoring


- name: Enable and start smartd service
  ansible.builtin.service:
    name: smartd
    enabled: yes
    state: started
  tags:
    - monitoring
