---
- name: Install NFS server packages
  ansible.builtin.package:
    name:
      - nfs-utils
      - rpcbind
    state: present
  tags:
    - nfs

- name: Enable and start rpcbind service
  ansible.builtin.service:
    name: rpcbind
    enabled: true
    state: started
  tags:
    - nfs

- name: Generate NFS exports file
  ansible.builtin.template:
    src: exports.j2
    dest: /etc/exports
    owner: root
    group: root
    mode: "0644"
  notify: Reload NFS exports
  tags:
    - nfs

- name: Enable and start nfs-server
  ansible.builtin.service:
    name: nfs-server
    enabled: true
    state: started
  tags:
    - nfs

- name: Disable NFS delegation
  ansible.posix.sysctl:
    name: fs.leases-enable
    value: 0
    state: present
    sysctl_set: yes
  notify:
    - Restart nfs-server
  tags:
    - nfs
