---
- name: Set share options for downloads user/group
  ansible.builtin.set_fact:
    smb_shares: >
      {{ smb_shares | map('combine', {
        'user': 'downloads',
        'group': 'downloads',
        'force_create_mode': '0665',
        'force_directory_mode': '0775'
      }) | list }}
  when: smb_shares is defined and smb_shares | length > 0
  tags: samba

- name: Configure Samba server
  ansible.builtin.include_role:
    name: vladgh.samba.server
  vars:
    samba_users: "{{ users }}"
    samba_shares: "{{ smb_shares }}"
    samba_load_homes: true
    samba_server_min_protocol: SMB2
    samba_server_max_protocol: SMB3
    samba_server_interfaces:
      - lo
      - eth0
    samba_server_bind_interfaces_only: true
  when: smb_shares is defined and smb_shares | length > 0
  tags:
    - samba

- name: Open Samba ports in firewalld
  ansible.posix.firewalld:
    service: samba
    permanent: true
    state: enabled
    immediate: true
  when: smb_shares is defined and smb_shares | length > 0
  tags:
    - samba
