apiVersion: v1
kind: Service
metadata:
  name: echo
  namespace: {{ .Release.Namespace }}
  annotations:
    dns.internal/enabled: "true"
    dns.external/enabled: "true"
    dns.external/target: home.{{ .Values.domain }}
spec:
  selector:
    app: echo
  ports:
    - name: http
      port: 80
      targetPort: 8080
    - name: logs
      port: 8081
      targetPort: 8081
