{
  "kind": "SealedSecret",
  "apiVersion": "bitnami.com/v1alpha1",
  "metadata": {
    "name": "cloudflare-api-token",
    "namespace": "kube-system"
  },
  "spec": {
    "template": {
      "metadata": {
        "name": "cloudflare-api-token",
        "namespace": "kube-system",
        "annotations": {
          "reflector.v1.k8s.emberstack.com/reflection-allowed": "true",
          "reflector.v1.k8s.emberstack.com/reflection-allowed-namespaces": "cert-manager",
          "reflector.v1.k8s.emberstack.com/reflection-auto-enabled": "true",
          "reflector.v1.k8s.emberstack.com/reflection-auto-namespaces": "cert-manager"
        }
      },
      "type": "Opaque"
    },
    "encryptedData": {
      "api-token": "AgCktkCNu1sMeJB6/NFhAzGpcYlULBawlw6xzhKtT7UuCdGRelidfs6Wy6/pz6gpdQmn1ZKwaa7HHSwtIIXPoXcGwL1P1KLFwxMWM06PaTuc3Hn0T2yKmeXgzIAibI8aVy39DaJuvbutI4sP4Q848At8la54Y/c9+F90vzPHvxZzWEFVD5RVSEllyTugqj63+y9OxC8amSH+wEDRjTUpy/nWMcb9hmcN+1WHMZL/KpbD09tK3b0Qpp4j7OpH04vdjOYw0uffzrJraRy6UT4LrOsOJC9aX7BBU4kYNYvdAmrjyQtZ2tKiePtkC44YV5FLtghKPXy0awKRsxfXHXgN/Zq/tJcE8Rlenti/8DFHQUL5+avpN6HwrTwbB9w1Svj3S2X469uRTeSgDOBvDU4Inx1pXULfKCNiJgABOol7dBEDeLRlUer0/p/7r4XN4wLSJtOY1Q2h9sUwgmOijqDTBRSY9a1DAnvW7Oly6/U5kEr3L9nLwFTBz5+Wb9wtA8HnuRdSmiRoTgFS7yuQmyRTqrNXiJGcGBxQUNtdv6x12BD9W37xm1XmArQdfXe+rZJsn4KJ/1pg0aYh6K3zvD8/lULs/KpSM/EjA2v89cPorulqO/wbu39+3yCHtoPagiwGexM6xCh33gR/PD5v3VXoIKiYKDlC5nVuoplSenDoR5+zjU27M5XxS9begTrMMqQS4qa6piPhDYL46rMV0BTv7XT+9Ee0WrwxM0YZRQ1VnHJAa7P5Xvqm7nKY"
    }
  }
}
