apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: pocketid
  namespace: {{ .Release.Namespace }}
spec:
  ingressClassName: traefik-public
  rules:
    - host: pocketid.{{ .Values.global.domain }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: pocketid
                port:
                  number: 1411
  tls:
    - hosts:
        - pocketid.{{ .Values.global.domain }}
      secretName: default-tls
