apiVersion: v1
kind: Service
metadata:
  name: pocketid
  namespace: {{ .Release.Namespace }}
  labels:
    app: pocketid
spec:
  selector:
    app: pocketid
  ports:
    - port: 1411
      targetPort: 1411
