apiVersion: apps/v1
kind: Deployment
metadata:
  name: ml
  namespace: {{ .Release.Namespace }}
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: ml
  template:
    metadata:
      labels:
        app: ml
    spec:
      securityContext:
        fsGroup: 0
      containers:
        - name: immich-ml
          image: ghcr.io/immich-app/immich-machine-learning:v2.0.1
          ports:
            - containerPort: 2283
          envFrom:
            - configMapRef:
                name: immich-config
            - secretRef:
                name: immich-secrets
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop: ["ALL"]
          livenessProbe:
            exec:
              command: ["python", "healthcheck.py"]
          readinessProbe:
            exec:
              command: ["python", "healthcheck.py"]
          volumeMounts:
            - name: model-cache
              mountPath: /cache
      volumes:
        - name: model-cache
          persistentVolumeClaim:
            claimName: immich-model-cache
