apiVersion: apps/v1
kind: Deployment
metadata:
  name: blackhole
  namespace: {{ .Release.Namespace }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: blackhole
  template:
    metadata:
      labels:
        app: blackhole
    spec:
      containers:
        - name: blackhole
          image: ghcr.io/justin8/http-https-echo:latest
          ports:
            - containerPort: 8080
              name: http
            - containerPort: 8081
              name: logs
