{{ include "common.pomeriumIngress" (dict
  "ctx" .
  "name" "blackhole"
  "subdomain" "blackhole"
  "port" 80
  "type" "public"
  "allowedUsers" "all"
) }}
---
{{ include "common.pomeriumIngress" (dict
  "ctx" .
  "name" "blackhole-logs"
  "subdomain" "blackhole-logs"
  "port" 8081
  "serviceName" "blackhole"
  "type" "public"
  "allowedUsers" "authed"
) }}
