apiVersion: cilium.io/v2
kind: CiliumNetworkPolicy
metadata:
  name: blackhole
  namespace: {{ .Release.Namespace }}
spec:
  endpointSelector:
    matchLabels:
      app: blackhole
  ingress:
    - fromEntities:
        - host
    - fromEndpoints:
        - matchLabels:
            k8s:io.kubernetes.pod.namespace: pomerium
            app.kubernetes.io/name: pomerium
      toPorts:
        - ports:
            - port: "8080"
              protocol: TCP
            - port: "8081"
              protocol: TCP
  egress: []
