apiVersion: apps/v1
kind: Deployment
metadata:
  name: pihole
  namespace: {{ .Release.Namespace }}
  labels:
    app: pihole
    pihole/type: primary
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pihole
      pihole/type: primary
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: pihole
        pihole/type: primary
    spec:
      containers:
        - name: pihole
          image: "{{ .Values.images.pihole.repository }}:{{ .Values.images.pihole.tag }}"
          imagePullPolicy: {{ .Values.images.pihole.pullPolicy }}
          ports:
            - name: dns-tcp
              containerPort: 53
              protocol: TCP
            - name: dns-udp
              containerPort: 53
              protocol: UDP
            - name: http
              containerPort: 80
              protocol: TCP
          resources:
            requests:
              cpu: 20m
              memory: 256Mi
            limits:
              cpu: 200m
              memory: 512Mi
          env:
            - name: FTLCONF_webserver_api_password
              value: ""
            - name: FTLCONF_dns_upstreams
              value: "9.9.9.9;1.1.1.1"
            - name: FTL_CMD
              value: "no-daemon -- --interface=eth0"
          volumeMounts:
            - name: etc-pihole
              mountPath: /etc/pihole
      volumes:
        - name: etc-pihole
          persistentVolumeClaim:
            claimName: pihole-etc-pihole
