{{- range $instance := list "primary" "secondary" }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: pihole-{{ $instance }}
  namespace: {{ $.Release.Namespace }}
  labels:
    app: pihole
    pihole/type: {{ $instance }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pihole
      pihole/type: {{ $instance }}
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: pihole
        pihole/type: {{ $instance }}
    spec:
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 100
              podAffinityTerm:
                labelSelector:
                  matchLabels:
                    app: pihole
                topologyKey: kubernetes.io/hostname
      containers:
        - name: pihole
          image: "{{ $.Values.images.pihole.repository }}:{{ $.Values.images.pihole.tag }}"
          imagePullPolicy: {{ $.Values.images.pihole.pullPolicy }}
          ports:
            - name: dns-tcp
              containerPort: 53
              protocol: TCP
            - name: dns-udp
              containerPort: 53
              protocol: UDP
            - name: http
              containerPort: 80
              protocol: TCP
          resources:
            requests:
              cpu: 20m
              memory: 256Mi
            limits:
              cpu: 200m
              memory: 512Mi
          env:
            - name: FTLCONF_webserver_api_password
              value: ""
            - name: FTL_CMD
              value: "no-daemon -- --interface=eth0"
{{- end }}
