# DNS record: storage.domain -> NFS/Tailscale IP
apiVersion: externaldns.k8s.io/v1alpha1
kind: DNSEndpoint
metadata:
  name: storage-dns-record
  namespace: {{ .Release.Namespace }}
  annotations:
    dns.internal/enabled: "true"
spec:
  endpoints:
    - dnsName: storage.{{ .Values.domain }}
      recordType: A
      targets:
        - {{ .Values.network.storageServer }}
---
# DNS record: authenticate.domain -> Pomerium ingress IP (Internal)
apiVersion: externaldns.k8s.io/v1alpha1
kind: DNSEndpoint
metadata:
  name: authenticate-internal-dns-record
  namespace: {{ .Release.Namespace }}
  annotations:
    dns.internal/enabled: "true"
spec:
  endpoints:
    - dnsName: authenticate.{{ .Values.domain }}
      recordType: A
      targets:
        - {{ .Values.network.pomeriumIngress }}
---
# DNS record: authenticate.domain -> home.domain (External)
apiVersion: externaldns.k8s.io/v1alpha1
kind: DNSEndpoint
metadata:
  name: authenticate-external-dns-record
  namespace: {{ .Release.Namespace }}
  annotations:
    dns.external/enabled: "true"
spec:
  endpoints:
    - dnsName: authenticate.{{ .Values.domain }}
      recordType: CNAME
      targets:
        - home.{{ .Values.domain }}
