{{- $ctx := . -}}
{{- $extraAnnotations := dict "traefik.ingress.kubernetes.io/router.middlewares" (printf "traefik-private-tinyauth@kubernetescrd,dns-pihole-redirect@kubernetescrd") -}}
{{- include "common.ingress" (dict "ctx" $ctx "name" "pihole-web" "subdomain" "pihole" "annotations" $extraAnnotations) -}}
