apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: pihole-redirect
  namespace: dns
spec:
  redirectRegex:
    regex: "^https?://pihole\\.{{ .Values.domain }}/?$"
    replacement: "https://pihole.{{ .Values.domain }}/admin/"
    permanent: false
