# Internal web service for external-dns to reach pihole API
apiVersion: v1
kind: Service
metadata:
  name: pihole-web
  namespace: {{ .Release.Namespace }}
  labels:
    app: pihole
spec:
  selector:
    app: pihole
    pihole/type: primary
  ports:
    - name: http
      port: 80
      targetPort: 80
---
# LoadBalancer service for DNS traffic (but on Tailscale)
apiVersion: v1
kind: Service
metadata:
  name: dns-tailscale
  namespace: {{ .Release.Namespace }}
  labels:
    app: pihole
  annotations:
    tailscale.com/hostname: pihole
spec:
  type: LoadBalancer
  loadBalancerClass: tailscale
  selector:
    app: pihole
    pihole/type: primary
  ports:
    - name: dns-udp
      port: 53
      targetPort: 53
      protocol: UDP
    - name: dns-tcp
      port: 53
      targetPort: 53
      protocol: TCP
