traefik:
  deployment:
    replicas: 2
  ingressClass:
    enabled: true
    isDefaultClass: false
  service:
    type: LoadBalancer
  providers:
    kubernetesCRD: {}
    kubernetesIngress: {}
  ports:
    web:
      http:
        redirections:
          entryPoint:
            to: websecure
            scheme: https
    websecure:
      transport:
        respondingTimeouts:
          readTimeout: 10m
          writeTimeout: 10m
          idleTimeout: 10m
  ingressRoute:
    dashboard:
      enabled: false
