{
  "kind": "SealedSecret",
  "apiVersion": "bitnami.com/v1alpha1",
  "metadata": {
    "name": "cloudflare-api-token",
    "namespace": "kube-system"
  },
  "spec": {
    "template": {
      "metadata": {
        "name": "cloudflare-api-token",
        "namespace": "kube-system",
        "annotations": {
          "reflector.v1.k8s.emberstack.com/reflection-allowed": "true",
          "reflector.v1.k8s.emberstack.com/reflection-allowed-namespaces": "cert-manager,dns",
          "reflector.v1.k8s.emberstack.com/reflection-auto-enabled": "true",
          "reflector.v1.k8s.emberstack.com/reflection-auto-namespaces": "cert-manager,dns"
        }
      },
      "type": "Opaque"
    },
    "encryptedData": {
      "api-token": "AgAJ9/B4agHnRWFqoNJ/H4XPwHm5UMkcYA3ehy5+Z6jwdp6rGWQC99SyOqL7g0cSuRBTkOW8suvQgUqZAzWxDKV5dLIbZXixOd90mHei+hwvpXcK1RFj6oQcST/D5Q4u4hXfnKP79879m2TfDWUxYAWk7I4ou0tv3WagEY2FacChTyzoSrXWAVZ26BsLUY30RVFuvkIOuulczvtXwt0JhhraX9lVC3ngSiVe4m54gvoRvk5wQOsS7JUERlb/Pw+NZbcy56zG02ypv5tQs3XsZr8Mbwuk7EXNuG3L4y+pt54NilP6pFmrjay5mhxFm0XMZdCYY/Hb6lJ7d91day8/UOmVp+qd2cBCLt670jAiwDveZCSGEBFOlAn1DibFaFvLA1mWY5eiifm0stklwZMd33ZO7YASTwGlMbyzQ8MhGEoGwVMQeFISfMaXKVXB7beybbyCiceWkGf+ssn2Z7ST+ADhP9QvpaJjlGB+lqzrR7ZVCoi8GqPvLa1rFqoulKOsYrEsGR0KsbvsFC6d06B3wPaS0DIbHIUkat1XaqrkDih2CsCc6lN++p3HXCQyX09wt/nbFE6o6xD7TmmkWkcMCFZmuPRgVRPdvH6G5QTr8QI0ODnhMd1CUyYaXyI8wCP7JUoLgvDApjNZXGehtlg3rYAmFKqNXfKuUG3YoTtKU9rW53tj61mVhvTS/5jIDnqOPwMjC6r35dWpBjF8JMGi/+k0+Z2VjMQnpx0ETQOyuwesiXCERB2inzLI"
    }
  }
}
