{
  "kind": "SealedSecret",
  "apiVersion": "bitnami.com/v1alpha1",
  "metadata": {
    "name": "cloudflare-api-token",
    "namespace": "kube-system"
  },
  "spec": {
    "template": {
      "metadata": {
        "name": "cloudflare-api-token",
        "namespace": "kube-system",
        "annotations": {
          "reflector.v1.k8s.emberstack.com/reflection-allowed": "true",
          "reflector.v1.k8s.emberstack.com/reflection-allowed-namespaces": "cert-manager,dns",
          "reflector.v1.k8s.emberstack.com/reflection-auto-enabled": "true",
          "reflector.v1.k8s.emberstack.com/reflection-auto-namespaces": "cert-manager,dns"
        }
      },
      "type": "Opaque"
    },
    "encryptedData": {
      "api-token": "AgDauMRih0E2KlckNQlvPVvjQYcTw+FbVE8EUd1xS9rDPVSvIMt4cQp39oHzAaJsmT1rGqM81HOUSwXJ4Sf4Rkv1P7laMkemh3ikH1bZe0sF3gvraYq4U0OcK+Ob5NyEp3YiGEruYEg2O0FYwbqFW54r8vgX/j/PgJmIjByZOxDKUMfTg1PbXSLdGbv//z3+Gl6Agm566Y+pw9A9mr+2c9JPnhKSdnbDUqO+2RL/xNxFWbK0GiHMN2opTCzD/h3vvt9UHu26VFgnR7gPWx03N9ctwgem6ZU0M7USX5+2dH3OriG3Gp+sSJCuJh28ApCp41QaRg0u5MQEuH+5wQKCuTwUzf7/7bmhy+lamC9eKRYWb1XvYWgP6Nu7xONfmHBOAcvfVx6lXPWQu1FaM63qMBWsqWV/9OmjkI/u6txa7IKWOq/4vqB4TOFrHTD1YnF1w3fhbds1ZBhnkcM57VUqttXLYdNKSayzxpsXFE/CmRo9DWdn4aeYj442G2c6TBytD5YUjMwYqzYR3gKj/cg7KiPTi5LcUNuWE2qwWGtT1NCeZakpyl9KY88p4h5TjK2Z4mpTnODV6yj3/cOKEMkipxGZ9XdkqxsThRYNSMACNeM0dPIfq3ZJTWmaPZY3LzyprTNxvkZjfrgsrEoaEEb7FN/Gjb8Ngy4fB2e5Mc4izPeutz4lf7S1MwBn9gi+P+Ai3aHNFZQ9iKci7CDRaEbKawLHDgeU3XdhSYgnJCX7fVP84xvXEXRled6g"
    }
  }
}
