{
  "kind": "SealedSecret",
  "apiVersion": "bitnami.com/v1alpha1",
  "metadata": {
    "name": "cloudflare-api-token",
    "namespace": "kube-system"
  },
  "spec": {
    "template": {
      "metadata": {
        "name": "cloudflare-api-token",
        "namespace": "kube-system",
        "annotations": {
          "reflector.v1.k8s.emberstack.com/reflection-allowed": "true",
          "reflector.v1.k8s.emberstack.com/reflection-allowed-namespaces": "cert-manager,dns",
          "reflector.v1.k8s.emberstack.com/reflection-auto-enabled": "true",
          "reflector.v1.k8s.emberstack.com/reflection-auto-namespaces": "cert-manager,dns"
        }
      },
      "type": "Opaque"
    },
    "encryptedData": {
      "api-token": "AgA1IO/e+0dEO2yYcXPNfcG/ehD5qng9uqdbcYa/9HLlesugfSk1NbtnC6cqWuf4Wde67l7A1ryhRlFCls7yrt4kiRjya1GPoj6gcT7RLOHuudz5mP6LG3ZtdFWbKKPP4TLD8Fyv2tJ6r4wBqBxJCd8jrW//b6EKndkh1IoflEztDTHCPss+LBt0AmapDwKBmhFRO06u/tf4MZiBQTPmUobhPCCsL/+iduN+mhLOFBvzfhDOD7LZ99DI4/JWKgO/XVqzsND19kVyCypnOqmKZ1j3hYYHsEk5h+tEJxAHgqTWCIQt006oUOY3DSE6B2Bm8jzmUkNL91+Zy+crH6n6+3p+9JDYFUQvps/Qc2HAAAn3KCvNaLmtNga9qMywTHieK+d6hUxkKEpOGmMmbPCQhRmv5YMhCWbMjnX5r7NDymVRV8pLpCijO+p/JVDguxgxstUnISTGDSJaio8AlIU4eoFZ3GZv/RVskqqPZZbo5PsvzQxyxprf2LdmXl+tWiTmH/OK6C2FSqkUzrqAWwRVQTbSVZIc5su6b+60DNcR6NC1qulMOFPQtmFBn2nOSwqdYuWZ2UHU9sAouqIzBWIEbALowaS0MAmlplT7xlLTmxkaGXBoYJ2cKYMIYLOflwkENk/Am7Nb7QlyujgUSnT8n6SBWChKJE0OOX1+e7b93pQQCO/9PeD9/M+aMdBy5BAM2TS2kVhmQRFmWRqMh1YFdqvcTmlXpIL8sNF2hgidwFdMZJ4GvlQbwRv6C3qt9DEeTtC35SBEeQ=="
    }
  }
}
