apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: cnpg-b2-credentials
  namespace: kube-system
spec:
  template:
    metadata:
      name: cnpg-b2-credentials
      namespace: kube-system
      annotations:
        reflector.v1.k8s.emberstack.com/reflection-allowed: "true"
        reflector.v1.k8s.emberstack.com/reflection-allowed-namespaces: "home-automation,immich"
        reflector.v1.k8s.emberstack.com/reflection-auto-enabled: "true"
        reflector.v1.k8s.emberstack.com/reflection-auto-namespaces: "home-automation,immich"
    type: Opaque
  encryptedData:
    AWS_ACCESS_KEY_ID: AgADVCH6DdTVmq123XARsTfDUxy7H4wiKsKGPlRHSYtk8WrJ2L5lwEUA93yKuvrQMXIrfUa5bGe8x1ZQua9IsNkV7hc1YoxmXINZq0gV+/OcaTNlkjDH9IxZQCb/a8rF5GJfx/uFNNAvZTCG/yjdGcjCflnBgwykRQtv325PTsVK0xg2qlLPJ3LFtPryogI46PC2bMOa8t3ks/C9eaiTymouITFGmDS/OF8Ngc6kNqKe7Fc+hE3MMvsZsAREBL3L2RPMPW6i4Gh8TJMqyTXMiIwDk1/pqHHNsDiGPwxDLFHBaILKQkjMErNsjDThQXd9zt8/ac07XC/qwNRmaBjXEXIUp4n3f9VGlCxP1VjJGGQzb2FAqvgsvHGGLF1W2MHB7ltschM5DrCAqhP/5Gtf81in9mWUpLEfP6sy21Lxm29BXH7MxWpvg9xysPxXb26iKlJIxBSfHhMlUSeaeWlakawnkopTBpjEWq0zkqraWVbe3JivhnClfwF+GU1zvRHpKMY/4bt22IyIaxM3Ps7xC0Z8R/BqXYo7KlUD8yS8/hGGU9etsisAmeiJQD8CwG57ZIwCIfe6XCeguCRlT76VsGPN5oRmi860UMn4acySFg6/bDFTFlUFxdx6Qb4uoMbZUrfh3OABXpxl7UBR1wddCbyzwiPReYhJwLpfh9ODfXaXQz394vhAw9Lxts/PLfFFK2ygrypTEgocjHZ9zaFFef2OEiLjIkUeEbDA
    AWS_SECRET_ACCESS_KEY: AgDEu5JO/Z4XcWbHppAluqWCPV3Ydzj4P1gC9PdulLgZC9fbRHHDegY12PF2BY6uBJ81RWa8hGGzWs6rZbthNMiLeJgZUt75DwIHK7ZsgTbYPiYioLAV52IDBx23etzUhkSeq7DUT0DCo8tDLPrsjtwHXG88PVyMk2g4c1P0SSlx+VafYm7Wn4Ul7Ypdvx00zr5GH1FTboOvtLmJMehKb4VYOxZSUBEczEcuiqyAjjv6Qe3wHGDdLSBc63TJxCF69KNTacLjpyBr2DlDZZhbnxPBJ5IcrDMQlWGoJwxCV+oT8T47RY6i8fTNqfvtHIrdSiNgUhowN7+BDGOMy57mOJ66guQqG0kyIGm2LX3rYF8s0zqDAgvpTzlbwsNyntE0jkokvs78I+LkfSpCKFKm7lkb+cAT2xCweGAdO0B8rqJAsYtzN8MxRTiAXbwXH6utFv1vF9eJa2GZxw1ZnbC/hyLob6WemtQsvD9wOmJTgbC55I9b70lkZHV8FtrpmB15eUrvd7U+yrSIPcUDznrgDMAHO8Ve9LId0iHn3suG+B6hniRQ/3qhY+MDD5v8GZ9Z5busX3zRlyUf6k1AdM6CZV9rJ62sWG5KoRcjwMAfAtkbVVt8GGsY5Vq/FOK04R3r5o2qDd03vJ+m4wc12o9hDKDRyCzfTly6s83QcRM/vUutSwkspVju8LU+9hvv3bhYyB2pGREx7/A9+vgrQNPCLgzxXmg+fq5/RLsO0OIyUlzu
