apiVersion: cilium.io/v2
kind: CiliumNetworkPolicy
metadata:
  name: kavita
  namespace: {{ .Release.Namespace }}
spec:
  endpointSelector:
    matchLabels:
      app: kavita
  ingress:
    - fromEntities:
        - host
    - fromEndpoints:
        - matchLabels:
            k8s:io.kubernetes.pod.namespace: pomerium
            app.kubernetes.io/name: pomerium
      toPorts:
        - ports:
            - port: "5000"
              protocol: TCP
  egress:
    - toCIDRSet:
        - cidr: {{ .Values.network.pomeriumIngress }}/32
        - cidr: {{ .Values.network.privateIngress }}/32
      toPorts:
        - ports:
            - port: "443"
              protocol: TCP
    - toEntities:
        - world
