apiVersion: pocketid.internal/v1alpha1
kind: PocketIDOIDCClient
metadata:
  name: kavita
  namespace: {{ .Release.Namespace }}
spec:
  name: Kavita
  callbackUrls:
    - https://kavita.{{ .Values.domain }}/signin-oidc
