apiVersion: v1
kind: Service
metadata:
  name: grist
  namespace: {{ .Release.Namespace }}
  labels:
    app: grist
spec:
  selector:
    app: grist
  ports:
    - port: 8484
      targetPort: 8484
---
apiVersion: v1
kind: Service
metadata:
  name: redis
  namespace: {{ .Release.Namespace }}
  labels:
    app: redis
spec:
  selector:
    app: redis
  ports:
    - port: 6379
      targetPort: 6379
---
apiVersion: v1
kind: Service
metadata:
  name: apicache
  namespace: {{ .Release.Namespace }}
  labels:
    app: apicache
spec:
  selector:
    app: apicache
  ports:
    - port: 80
      targetPort: 8080
