apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: homeassistant-db-password
  namespace: home-automation
spec:
  template:
    metadata:
      name: homeassistant-db-password
      namespace: home-automation
    type: kubernetes.io/basic-auth
  encryptedData:
    password: AgDDoNj7/DmRopdF0vq1I4wzzRs6cIWanwumANduKBmViiYUwr3qL3rg4PfU5mMD7Nl9ed2TCv+/QlCvKmfA7/KnZNrjm1d5Xtl0tHE/EMIR+i6L/QkVnrfFtKfFS2YyA9c5vFtwD0TiWI50hqi4Tsa/4rDuoCORv4wPRrLUFpC3mo0FlWp8ae3QkgA3J/6ym70q92tcxDGUla86SoVhxAqF8L74cOrGQx+885b5DVrNKpuNTvkNbac2VrbyReXtFOiGgcIdCufhibBAk4DXDs+/4kSHyrSNMt366OC9YpXC36c3iym2ldXak4VL8x7Rsn0BB2wmvq7KfaMAr+CywzPtE5GaWM5yrtSH7tqoVddktt3MbF/nnUPCgKJcjiE0YjsKoq39cedzNJxFsTkolR45ReTa00r+ajqO2X7zteoaR29KEnNKyP3zjxjKd1Mu8Y+dKwpqGq+gYXZcXW53QUG+RKLNLQruihtyDem5hnQ9eb4AYbBqaLGw1L8ktB4tLohI73lcBgI/pZKEbM9MnwhpHnRV6Yf0IxrVkIUKOpxlBwTaSHnAA6khJPUQ/LxT4R4aiH/AduCDDelZcUx2PB1goqjT7PaQX2NorJmnJism51iwb7F2Sv6A4iDLZG3iVtunbq/+NNMmiGO3FtGZG7L0Fbxj4hmZo4dG+16z2CbXrJAD58NJPHjZN9vpd2mQnNWToH+lhOlOXdDrgLf5Y8wKNYUI3saQwpXUGv5JUqU/PA==
    username: AgAbLz3r1X8HZ+1KUXyeQp/OEjJFFaNj1VgzLELT50/+HeTjMWbs893PWTV6BLOFDARfCS/9B/eNa0mAg8uOYAQDhdZtneNjE+RPsAQPUMINi7f5teXo9oiZlCHr5AFCkaC4teXQA7fGw5+XJh85srFGmh3kYjzkwRAXiazDXAgeFaie5ULR+og/imGV3IFbjAsBtQMxBOERgMsKYa9neq9M71+ovOwhnmxcXN50trwfFDv1kevxCEvmAU/jV4zNdgtOC8EQoiDsREW/ZD5P/LQgjCnSivzhnrvS324VnNuA6NWlC86GBRkVkiu8Az/EcLQa0taB68lyKf0yDhtQH3MDr21plUMdg9/WuWircdfwiTnenrSoz4O5jirmrpE5y/mvCEs8ItEPmKZiv0a+Xon0FitrgjVjnmtdmpgW27IwKy/GStC/S9irDu4oPUVhKaiVoAZ9Pj12nrAnDkoCXPTLE3gpnpPnVRx+YxG6HUHpTrq3xTmx9AqJxMYwAyOltzUhcdxtkxDEcp3pwxYFGBNSW95+p4DOB9xr13YMMqNA2OBpVEj+4j29SHSlLZJcbYrVbAnWPHFrKhRHRNbgFS/QdQzx47eZ6Byp+Rte+Sdfr49jbDluixFBlQMgxEbj1FGjQwgeptOAy7d4pDlOzkDryyeiiGRFI+MqF8AZ2kYjsUBmYQkOaSDRrlp1DKCKCIQW13vyL9WuAJ3wp4mJVmGpqOo=
