apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: homeassistant-db-password
  namespace: home-automation
spec:
  template:
    metadata:
      name: homeassistant-db-password
      namespace: home-automation
  encryptedData:
    password: AgAtVEivjcqM1BDEPrCOFcqQOq+eAU7p4mbxaeQbbbrOlJ6LLOsU3WGIcRK7S41Xt9kUtFqExfYgFp6cJ+v5V6Jk+0+IYJtGMDPcxmZ1OObCRWLKwyhLj6JYc4no3FEKETNMYLrwd1kazd8vr+otgpHNbJ4Gb26CJN6aHutWfqG7Y9WIkdgu4H4+A1kbbhZV/dFcU2fSdOz2wfuXx8xkwEUhVt1ZJnmjpF+a6HILvQPGYtZaTIhOtDR0bYsMUV65/hCvJU8RLjpfJ3mbbZrtD5GBvFOPYilmqlmdVzT9YghRhvav3ZKwWYc3X+PLBb2hhhPs2igU5MqJW9vjvJtnt8p2j/8RUCItTelAm5Phh/MdjKGUrlvFqVt4s8EiuR1M9G3y/iS/A8uofy3IBWqVLZkw8lpjr8Fi25DNhnkp/l7HLsweKBsRxuCFyGZH24fHqn7ZrMmqMNJ4R6vN8vu1bBh1sGUvqln78ealN7ZsYpRsDtlVPZ/Jj2Yql2cn19gshIrxEw+oLktCOs3Iz5tflwflMwq6RoN6UzUIy+2yhwza1CAqOf2KDV1rPkjQ0fEJwfMe+kRAX/5seJDcz16dw4nThVPp2+p4fEgbOYzv0/MA34Mzu+u3+/rQGy7ynLIJnlRIZKtRa5XQk6OQd7XMsp54KUU9CjmF0PjN1fLPjtlSMY6pXt+wR1OySsQs8geAuT92DIR3a8Bd/PKfvSt4Q9gzm4q0odWtiK2O4UnjdKZakw==
