apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: home-assistant
  namespace: {{ .Release.Namespace }}
spec:
  ingressClassName: traefik-public
  rules:
    - host: home-assistant.{{ .Values.domain }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: home-assistant-http
                port:
                  number: 8123
  tls:
    - hosts:
        - home-assistant.{{ .Values.domain }}
      secretName: default-tls
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: home-assistant-private
  namespace: {{ .Release.Namespace }}
spec:
  ingressClassName: traefik-private
  rules:
    - host: home-assistant.{{ .Values.domain }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: home-assistant-http
                port:
                  number: 8123
  tls:
    - hosts:
        - home-assistant.{{ .Values.domain }}
      secretName: default-tls
