{{- include "common.ingress" (dict "ctx" . "type" "traefik-private" "name" "home-assistant-http" "subdomain" "home-assistant" "port" 8123 "auth" false) }}
---
{{- include "common.ingress" (dict "ctx" . "type" "traefik-public" "name" "home-assistant-http" "subdomain" "home-assistant" "port" 8123 "auth" false) }}
