---
- name: Install system packages
  ansible.builtin.package:
    name:
      - cronie
      - curl
      - git
      - msmtp
      - uv
      - zsh
    state: present
  tags:
    - users
    - email
    - snapraid

- name: Ensure crond service is enabled and running
  ansible.builtin.service:
    name: crond
    state: started
    enabled: true

- name: Ensure system users exist
  ansible.builtin.user:
    name: "{{ item.name }}"
    state: present
    shell: /usr/bin/zsh
    uid: "{{ item.uid | default(omit) }}"
    password: "{{ item.password | default(omit) | password_hash('sha512') }}"
    groups: "{{ item.groups | default(omit) }}"
  loop: "{{ users }}"
  loop_control:
    label: "{{ item.name }}"
  tags:
    - users

- name: Ensure root has an ECDSA SSH key
  community.crypto.openssh_keypair:
    path: /root/.ssh/id_ecdsa
    type: ecdsa
    size: 521
    owner: root
    group: root
    mode: "0600"
    state: present
  when: not lookup('ansible.builtin.file', '/root/.ssh/id_ecdsa', errors='ignore')

- name: Create msmtp config
  ansible.builtin.template:
    src: msmtprc.j2
    dest: /etc/msmtprc
    owner: root
    group: root
    mode: "0600"
  tags:
    - email

- name: Symlink msmtp as sendmail
  ansible.builtin.file:
    src: /usr/bin/msmtp
    dest: /usr/sbin/sendmail
    state: link
    force: true
  tags:
    - email
