---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: immich-secrets
  namespace: immich
spec:
  encryptedData:
    REDIS_PASSWORD: AgCP9SwPpQkF6sq845fsRrmjylWQJwg8DuTETkPgty6JWDb9kCBhrxmTPi+wiY/rpjrTAERz+ykqqdq7aAuLvzQ/cfR5aG3Yiupc1ND421+HgODHcwC7fGtE9zX+QGclDbHNgx5gpmLx9jTm1unaaKkUvxqz2M/JKvtONQ7znowmDRTBRz2BrjLGJ6yO9HQPMieXixvn1imMrk3ewbLdkOYusJFEuucFqlSJx6TR22fdAzdBrmKQfBXlxs6J0lZSCz6GwncZQISoQFaHuUOytsNm2BLjNtlFM+oY+edVLekJrOfCKgAGy9Cw6mpZE0v3zcIRvvcR/3pzff4Zwxd0EEg1KU9JF/o7qKgSgUlIjnWDZtKFEHnsAhFGdNJLL1BfjUN8geU3aCXoZOS05aPm89ZJDyRLU3ZJeiwDPuwUPUiBSHZ5Pt02r6//1ag6vjSS2IDgqcdEjY8YTo11B0bBcqEm6ekMVpZICiamopUSafZQerpX1mH9OpTMzsr4hdE06lK39SJhX1JRWYKdLg8Uq3iXbFm5lN1xipRU4KbWDs0ts6W6s72FXkPxYWaFvKVZfX96QaSbGv7WmPiRAypuvJKv8Y77if1iyVKEJHQPqJk7oSRVOp3T5UOkwwUVmCvs/tOv0k/tl8n+5xBLP3hU/FmCGKnxpO1nSgpyy+4MW3GU+cHhrMkRW+i40dKAWqrDFsc//2LsbfIQUIapeInZYY4kvZ3N4TWWgdcBTU/hwFcO
  template:
    metadata:
      name: immich-secrets
      namespace: immich
