---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: immich-secrets
  namespace: immich
spec:
  encryptedData:
    REDIS_PASSWORD: AgDZHByGLMzJjpLe+06VTmrIoovPaVhKl7DsXMMa6ExnmGSBgKhFxvcZnh3Grr6zDRGuPbns1Jg22MA+PJ4eCKj7JovUnFB9jTfkOMbxqR4M5HLELYvLDRyTsQ9bL4ZiOjE343AHIRT8dMZ3LaNSx4p7k8HFxtT4PvcC/yQHq27xOZ1n0WxHxsrGZQRjKwNsMznk5B/9ptCETSjgs+MQm0NviFtD9KAqTQ8N+vJK3+r4fYZtP1gvSQddm+6Q9DAvM/Yh2tUDn+NPrU422fXUSb6TKqR5CFnJYX7yXGDZITk/dZJTA/alRe9oHbwseelkFoAGWNG5Ky/+LeWbLj5diSLyAQidY8gcJQdN8mn4xW6EEhVGZyuUP0kszAljcLph7Wyxc4C4rPuaFbmcTeCbRqF73PJyXw3lgzgQwEbRth3zgos+iAaJwizIt7XKDV+beluVu2ieMaKkYbZXToL2wxAS18D/gS11HL8Tb5WAICBbYDPkcl647BB8V0r/SUxus8RKIaD0RYMnQb45+B5hOKkGURIDYcKRquzYjTBJkuTG6Reolx6ZE5U8abpLqS9vXTDe1rmdco6GMv9yFcBOOPA7wXaNlZH6YDIqbwsGBgALGX3hV1WWwYT2hqVhgcqrO3ih+Kr2g9kKMWpqlBZfWRJiAIzr1Et4iDHJLad+QRvUL4UMO51s0q2eF0Zy/aA3ycibaY/LUxMvuesYw2BqqH1nPgtdfc7oTc/xDkNeS1VWrhBjIb9a8SH6K16NLzQmzL0=
  template:
    metadata:
      name: immich-secrets
      namespace: immich
