apiVersion: apps/v1
kind: Deployment
metadata:
  name: zigbee2mqtt
  namespace: {{ .Release.Namespace }}
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: zigbee2mqtt
  template:
    metadata:
      labels:
        app: zigbee2mqtt
    spec:
      containers:
        - name: zigbee2mqtt
          image: "{{ .Values.images.zigbee2mqtt.repository }}:{{ .Values.images.zigbee2mqtt.tag }}"
          imagePullPolicy: {{ .Values.images.zigbee2mqtt.pullPolicy }}
          ports:
            - containerPort: 8080
              name: http
          env:
            - name: TZ
              value: {{ .Values.TZ }}
            - name: ZIGBEE2MQTT_CONFIG_MQTT_BASE_TOPIC
              value: zigbee2mqtt
            - name: ZIGBEE2MQTT_CONFIG_MQTT_SERVER
              value: "mqtt://mqtt.{{ .Release.Namespace }}.svc.cluster.local"
            - name: ZIGBEE2MQTT_CONFIG_MQTT_USER
              valueFrom:
                secretKeyRef:
                  name: mqtt-z2m-credentials
                  key: username
            - name: ZIGBEE2MQTT_CONFIG_MQTT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mqtt-z2m-credentials
                  key: password
            - name: ZIGBEE2MQTT_CONFIG_SERIAL_ADAPTER
              value: zstack
            - name: ZIGBEE2MQTT_CONFIG_SERIAL_PORT
              value: {{ .Values.zigbeeAdapter }}
          volumeMounts:
            - name: data
              mountPath: /app/data
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: zigbee2mqtt-data
