apiVersion: apps/v1
kind: Deployment
metadata:
  name: zigbee2mqtt
  namespace: {{ .Release.Namespace }}
spec:
  replicas: 0
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: zigbee2mqtt
  template:
    metadata:
      labels:
        app: zigbee2mqtt
    spec:
      containers:
        - name: zigbee2mqtt
          image: ghcr.io/koenkk/zigbee2mqtt:2.9.1
          ports:
            - containerPort: 8080
              name: http
          env:
            - name: TZ
              value: {{ .Values.TZ }}
          volumeMounts:
            - name: data
              mountPath: /app/data
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: zigbee2mqtt-data
