{{ include "common.pomeriumIngress" (dict
  "ctx" .
  "name" "zigbee2mqtt"
  "port" 8080
  "allowedUsers" "admin"
  "responseHeaders" (dict "Content-Security-Policy" (printf "frame-ancestors 'self' https://home-assistant.%s" .Values.domain))
) }}
