apiVersion: v2
name: openclaw
description: A Helm chart for OpenClaw
type: application
version: 0.1.0
appVersion: "latest"
dependencies:
  - name: common
    version: 0.1.0
    repository: "file://../../common"
