---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: uhf-secrets
  namespace: uhf
spec:
  encryptedData:
    PASSWORD: AgCbUrkokTRFwIeIywQTHDV4JzPw6JLicfij/bHb1QfATWO2mu90BO1c4EQg4XWYEeHhFbziZUFrvT1AljgNlH23ez4lY9P53rFpQvDmxOdn2YQQKoloy7NPC+OUOUsG6j4kNWb+HrxSGEeNLGqhSHm22DS9mEXF/F5dG2WYclhTweqx11CvyRwz69UpEXnBGnqaut5ERaC/8jtSIoJEbavQNomnf14WXVTqaIap2e1wmtV69hN+QfdK+P5CKCZyMxRvG8zTICVL8ji70BqS5zQzbZhlOwur5VEwRpTZS/L84MTjmGnoUfWD+PQFBLhvdDEkU3zt/78g7lODAoy7RXqOf8SBNQY/8sQuNI+R3cw9WgoC1crKixbZp9Rbh7OsCYBKqf/Z4VUSDwXOVxyBxc++dq7E3ujRYO8h00ynQSLSpmTN8N7aOt7ZzKfzU0eu2RmQDyF+rRUVHoQ1XaJOiF7/4Rib9doEgHMFL6jsNDzM2NopC7hWVGiJ1xpQFWdtjR4BL0m4qdn6vm3Uo+RyeATeCfCgtur7qiTIEUE/eSg4+ecwy34HqjxwUlmEPBtlO5NFsu0uexpw11TMvUT9/0DNA1OsWbNuQmGMXxBLYC2Uj8MEDC7NwwATcFmRewRBZ6Av/X2bMFM4zRAr5oPFP0wOjsEGIvk+HEZJJEhx49iLeaNHZK68JKlCLNzGlJTualsJPkRgKYl7twoxUOdJPzKD
  template:
    metadata:
      name: uhf-secrets
      namespace: uhf
