apiVersion: v1
kind: Service
metadata:
  name: uhf
  namespace: {{ .Release.Namespace }}
  labels:
    app: uhf
  annotations:
    dns.internal/enabled: "true"
    dns.internal/hostname: uhf.{{ .Values.domain }}
spec:
  type: LoadBalancer
  selector:
    app: uhf
  ports:
    - name: tcp
      port: 8000
      targetPort: 8000
      protocol: TCP
