apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mail-proxy-spool
  namespace: {{ .Release.Namespace }}
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn
  resources:
    requests:
      storage: 100Mi
