apiVersion: v1
kind: Service
metadata:
  name: smtp
  namespace: {{ .Release.Namespace }}
spec:
  type: ClusterIP
  ports:
    - port: 587
      targetPort: smtp
      protocol: TCP
      name: smtp
  selector:
    app: mail-proxy
