domain: "" # Overridden by global values

images:
  app:
    repository: ghcr.io/paperless-ngx/paperless-ngx
    tag: "2.20.15"
    pullPolicy: IfNotPresent
  redis:
    repository: docker.io/library/redis
    tag: "8"
    pullPolicy: IfNotPresent
  gotenberg:
    repository: docker.io/gotenberg/gotenberg
    tag: "8.32"
    pullPolicy: IfNotPresent
  tika:
    repository: docker.io/apache/tika
    tag: "3.3.0.0"
    pullPolicy: IfNotPresent

dataVolumeSizeGi: 5
mediaVolumeSizeGi: 20

service:
  port: 8000
