apiVersion: autoscaling.k8s.io/v1
kind: VerticalPodAutoscaler
metadata:
  name: pihole-primary
  namespace: {{ .Release.Namespace }}
spec:
  targetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: pihole-primary
  updatePolicy:
    updateMode: "InPlaceOrRecreate"
    minReplicas: 1
---
apiVersion: autoscaling.k8s.io/v1
kind: VerticalPodAutoscaler
metadata:
  name: pihole-secondary
  namespace: {{ .Release.Namespace }}
spec:
  targetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: pihole-secondary
  updatePolicy:
    updateMode: "InPlaceOrRecreate"
    minReplicas: 1
---
apiVersion: autoscaling.k8s.io/v1
kind: VerticalPodAutoscaler
metadata:
  name: cloudflare-ddns
  namespace: {{ .Release.Namespace }}
spec:
  targetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: cloudflare-ddns
  updatePolicy:
    updateMode: "InPlaceOrRecreate"
    minReplicas: 1
---
apiVersion: autoscaling.k8s.io/v1
kind: VerticalPodAutoscaler
metadata:
  name: dns-external-dns-cloudflare
  namespace: {{ .Release.Namespace }}
spec:
  targetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: dns-external-dns-cloudflare
  updatePolicy:
    updateMode: "InPlaceOrRecreate"
    minReplicas: 1
---
apiVersion: autoscaling.k8s.io/v1
kind: VerticalPodAutoscaler
metadata:
  name: dns-external-dns-pihole
  namespace: {{ .Release.Namespace }}
spec:
  targetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: dns-external-dns-pihole
  updatePolicy:
    updateMode: "InPlaceOrRecreate"
    minReplicas: 1
---
apiVersion: autoscaling.k8s.io/v1
kind: VerticalPodAutoscaler
metadata:
  name: dns-external-dns-pihole-secondary
  namespace: {{ .Release.Namespace }}
spec:
  targetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: dns-external-dns-pihole-secondary
  updatePolicy:
    updateMode: "InPlaceOrRecreate"
    minReplicas: 1
