apiVersion: v1
kind: Service
metadata:
  name: tinyauth
  namespace: {{ .Release.Namespace }}
  labels:
    app: tinyauth
spec:
  selector:
    app: tinyauth
  ports:
    - port: 3000
      targetPort: 3000
