apiVersion: longhorn.io/v1beta2
kind: Volume
metadata:
  name: tinyauth-data-v2
  namespace: longhorn-system
  labels:
    recurring-job-group.longhorn.io/backups-enabled: enabled
    recurring-job-group.longhorn.io/fstrim-enabled: enabled
spec:
  size: "209715200"  # 200Mi
  numberOfReplicas: 1
  dataLocality: best-effort
  accessMode: rwo
  frontend: blockdev
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: tinyauth-data-v2
spec:
  capacity:
    storage: 200Mi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: longhorn
  csi:
    driver: driver.longhorn.io
    fsType: ext4
    volumeHandle: tinyauth-data-v2
    volumeAttributes:
      numberOfReplicas: "1"
      dataLocality: best-effort
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: tinyauth-data-v2
  namespace: {{ .Release.Namespace }}
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn
  volumeName: tinyauth-data-v2
  resources:
    requests:
      storage: 200Mi
