apiVersion: v2
name: auth
description: Authentication services - PocketID
version: 0.1.0
dependencies:
  - name: common
    version: 0.1.0
    repository: "file://../../common"
  - name: pocket-id-operator
    version: 0.6.0
    repository: "oci://ghcr.io/aclerici38/charts"
