pocketidVolumeSizeGi: 1
tinyauthVolumeSizeGi: 1

images:
  pocketid:
    repository: ghcr.io/pocket-id/pocket-id
    tag: v2.5.0
    pullPolicy: IfNotPresent
  tinyauth:
    repository: ghcr.io/steveiliop56/tinyauth
    tag: v5.0.7
    pullPolicy: IfNotPresent
pocket-id-operator:
  instance:
    enabled: false
