domain: dray.id.au
adminEmail: admin@dray.id.au
clusterName: home-cluster
TZ: America/Los_Angeles
PUID: "2000"
PGID: "2000"
appStoragePath: /mnt/pool/apps
# Shared IP addresses
network:
  lanIpRange: "192.168.5.0/24"
  tailscaleIpRange: "100.64.0.0/10"
  clusterPodNet: "10.244.0.0/16"
  publicIngress: "192.168.5.3"
  pomeriumIngress: "192.168.5.4"
  metallbRange: "192.168.5.80-192.168.5.100"
  privateIngress: "100.71.142.73"
  storageServer: "100.92.202.28"
  dnsServer: "192.168.5.53"
userGroups:
  admin:
    - "b26fb09c-67fb-4cc3-bbf3-c242f47838f2"
  private:
    - "b26fb09c-67fb-4cc3-bbf3-c242f47838f2"
    - "4f1efca6-1f08-4895-9e00-24886fea2585"
