global:
  domain: dray.id.au
  admin_email: admin@dray.id.au
  clusterName: home-cluster
  timezone: America/Los_Angeles
  shared_uid: "2000"
  shared_gid: "2000"
  # Shared IP addresses
  network:
    metallbRange: "192.168.5.60-192.168.5.79" # change to 80-100 later
    publicIngress: "192.168.5.22" # change to .2
    privateIngress: "192.168.5.23" # change to .3
    storage: "192.168.5.5"
    cluster: "192.168.5.20"
    dnsServer: "192.168.5.253" # change to .53
