apiVersion: apps/v1
kind: Deployment
metadata:
  name: esphome
  namespace: {{ .Release.Namespace }}
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: esphome
  template:
    metadata:
      labels:
        app: esphome
    spec:
      hostNetwork: true
      dnsPolicy: ClusterFirstWithHostNet
      containers:
        - name: esphome
          image: "{{ .Values.images.esphome.repository }}:{{ .Values.images.esphome.tag }}"
          imagePullPolicy: {{ .Values.images.esphome.pullPolicy }}
          ports:
            - containerPort: 6052
              name: http
          livenessProbe:
            httpGet:
              path: /
              port: 6052
            initialDelaySeconds: 60
            periodSeconds: 30
          env:
            - name: TZ
              value: {{ .Values.TZ | quote }}
            - name: ESPHOME_DASHBOARD_USE_PING
              value: "true"
          volumeMounts:
            - name: config
              mountPath: /config
      volumes:
        - name: config
          persistentVolumeClaim:
            claimName: esphome-config
