apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argo-cd
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "-2" # Manage itself before everything else
spec:
  project: default
  source:
    path: kubernetes/charts/argo-cd
    repoURL: {{ .Values.global.repoURL }}
    targetRevision: {{ .Values.global.targetRevision }}
    helm:
      valueFiles:
        - ../../values/global.yaml
      values: |
        argo-cd:
          configs:
            cm:
              users.anonymous.enabled: "true"
            rbac:
              policy.default: role:admin
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
