apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nfd
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  project: default
  source:
    repoURL: https://github.com/kubernetes-sigs/node-feature-discovery.git
    path: deployment/base
    targetRevision: v0.17.4
  destination:
    server: https://kubernetes.default.svc
    namespace: node-feature-discovery
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
    managedNamespaceMetadata:
      labels:
        app: node-feature-discovery
        pod-security.kubernetes.io/enforce: privileged
        pod-security.kubernetes.io/audit: privileged
        pod-security.kubernetes.io/warn: privileged
