---
# A *very* minimal dns update for the one openwrt router in my network
- name: Create dnsmasq hosts file from template
  ansible.builtin.template:
    src: dnsmasq.hosts.j2
    dest: /etc/dnsmasq.hosts
    owner: root
    group: root
    mode: "0644"
  notify: Restart dnsmasq
