#!/usr/bin/env bash
# Usage: get-secret [secret-name] [-n <namespace>]
set -euo pipefail

kubectl get secret "$@" -o json \
  | jq -r '
    if .kind == "List" then
      .items[] | .metadata.name as $name | .data // {} | to_entries[] | "\($name) \(.key): \(.value | @base64d)"
    else
      .data // {} | to_entries[] | "\(.key): \(.value | @base64d)"
    end'
