apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Chart.Name }}
  labels:
    app: {{ .Chart.Name }}
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: {{ .Chart.Name }}
  template:
    metadata:
      labels:
        app: {{ .Chart.Name }}
    spec:
      securityContext:
        fsGroup: {{ .Values.PGID | default 2000 }}
        fsGroupChangePolicy: OnRootMismatch
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.images.app.repository }}:{{ .Values.images.app.tag }}"
          imagePullPolicy: {{ .Values.images.app.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.service.port }}
              protocol: TCP
          env:
            - name: ACTUAL_DATA_DIR
              value: /data
            # OIDC Configuration
            - name: ACTUAL_OPENID_SERVER_HOSTNAME
              value: https://budget.{{ .Values.domain }}
            - name: ACTUAL_OPENID_DISCOVERY_URL
              valueFrom:
                secretKeyRef:
                  name: actual-budget-oidc-credentials
                  key: discovery_url
            - name: ACTUAL_OPENID_CLIENT_ID
              valueFrom:
                secretKeyRef:
                  name: actual-budget-oidc-credentials
                  key: client_id
            - name: ACTUAL_OPENID_CLIENT_SECRET
              valueFrom:
                secretKeyRef:
                  name: actual-budget-oidc-credentials
                  key: client_secret
            - name: ACTUAL_USER_CREATION_MODE
              value: login # Create users automatically on first login
            - name: ACTUAL_OPENID_ENFORCE
              value: "true" # Force OIDC login

          volumeMounts:
            - name: data
              mountPath: /data
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: actual-budget-data
