apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Chart.Name }}
  namespace: {{ .Release.Namespace }}
  annotations:
    ingress.pomerium.io/allow_any_authenticated_user: "true"
    ingress.pomerium.io/policy: |
      - deny:
          and:
            - source_ip: {{ .Values.network.routerIp }}
spec:
  ingressClassName: pomerium
  rules:
    - host: budget.{{ .Values.domain }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ .Chart.Name }}
                port:
                  number: 80
