apiVersion: pocketid.internal/v1alpha1
kind: PocketIDOIDCClient
metadata:
  name: actual-budget
  namespace: {{ .Release.Namespace }}
spec:
  name: Actual Budget
  isPublic: false
  callbackUrls:
    - https://budget.{{ .Values.domain }}/openid/callback
