---
# tasks for dns role
- name: Install dnsmasq
  ansible.builtin.yum:
    name: dnsmasq
    state: present

- name: Copy custom hosts file
  ansible.builtin.copy:
    src: hosts.dnsmasq
    dest: /etc/hosts.dnsmasq
    owner: root
    group: root
    mode: "0644"

- name: Configure dnsmasq to use custom hosts and upstream DNS
  ansible.builtin.copy:
    dest: /etc/dnsmasq.d/custom.conf
    content: |
      domain-needed
      bogus-priv
      no-resolv
      addn-hosts=/etc/hosts.dnsmasq
      server=1.1.1.1
      server=9.9.9.9
      cache-size=10000

- name: Ensure dnsmasq is enabled and started
  ansible.builtin.service:
    name: dnsmasq
    state: started
    enabled: true
