apiVersion: v1
kind: ConfigMap
metadata:
  name: openclaw-config
  labels:
    app: openclaw
data:
  openclaw.json: |-
{{ .Files.Get "files/openclaw.json" | nindent 4 }}
  AGENTS.md: |-
{{ .Files.Get "files/AGENTS.md" | nindent 4 }}
