---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: openclaw-secrets
  namespace: openclaw
spec:
  encryptedData:
    OPENROUTER_API_KEY: AgCDVcNDlUIUjUT7pkJRkEGfeTLoVegZT+f9IoHfNGv3YrrWcnDxGMHdC8bPCX4A7mmkwAAYQvV8vrAkLiRAeVzjJF8H0ywWCvX0Xg4Zohu9ETPnvm+GVISff4F6Ix/nMgjWM++cwBYJJvFwp5aaGAn01KCJM5B9/QW5+JjvLtrdQLFlv+WrO4eQi9b1HUAf/5eEfumDiAObkNy9ZRNS90yUqe+HyE9L66tozMLCvkM8jIuMWkXBob0TTX4BRM3BGAYtw9nuahLNsNRvkBdCgypqzSMS6606+FY6asnrWP+di1GRKoaxtkqjqZB6ozx8qhnP7CWomh9cOaNgSpogG5ZApftA8iTpsjSyumYHD1h8PhblHy64tqJqDTYvUHf3tSZbK8OHuAR+4IXQJA3+w+YNGy9HZA+vXd182JTf6bgH8EzMy6W7TtpLJmS/+NAI9KNbm+4jFhceSxw8nDw5pBXcg68CKCV65+q3F8rkuXBjKCWLjFeUsVqFlSF1A4qMopHq4Wz2uiJnMwUBim6ufhQp1oCeTEyk2Zzc5cYGFfVENj42agzIH6nh1ib2O0WquDO86mPwxaQrbDjF0/xzS/DaGq/gd0Yl88yQZSCFNP5IdY2rOo4DVx81xayRmqVPv7+4peNvyXQDfsbpi2Rs96wHQFU3CUf3fzKq0KU6yTsTmVNPPj7nz7r8M8Zd7d4wNIyaugrXkRqvAiZYY2IQmlq+hRLEfm3GSE2WLBh6r90x9bkWldZlZH4VXqhqoii0pduXMt2hTjCi70fNIruHhLD52HH889gO/5MN
    TELEGRAM_BOT_TOKEN: AgBSoQ2GkOvaVXV/P78NGkFp7iWPO6AbMILKKnPQhuBWstt+zSx+v2/vNWeY8VOYKT8dypg9yPP6EE+7JWPoMdtEyJzzJKJHdscUw3aZiCCPD+ABVek1sx8FYp8mzIMtDog4mQP+lNtMtOpIPeyOLqqo2Z4kMR7hpXLT+OSFzjaEMhxfSdMNkD0j8XhMnRUZEa53AVyYpDEqF7AR58j4oe/7QMNfrs0oUDRnF5+/pKXFC0z8HbcFEme1FG5l3KiHOPI1urLc15ZMDicYpEMyf777TsE0L8+OVRjJ/5eJIcCCsJMZYiGt+MmE4s3o0enrg2WBr7ZNfzRvrB6VErouiaM89dnH4VYqJkkGnNYI5o3O4MKOhJTH9BFYmOQRE2s/kuJCC1cB5BKDgOHK/s7EqcCiZuqInuzCpjfr8Af18F4gQ5EBeS6BIFlxKgyjNQaLXCpBFVujgyKlfvalNd9wR1mgdk9hF227idjFvttl7yqW1vShOoHqMG0FdIOb5SROy86OMQ0xnh1ZM2rzWsfq101P03S6AQCZrnvQcQWg/34TZSvHWYBi+ATDgw2+IFZZ1LED6moS4kKwukxjGNs/tQTHnV1mglvxSM//TEQNR5fSasiR14MIEjGQ9+0ZWYkHWP2pqtcSSiBwcgG5acbpRi6WYz5NNgObjdUrlj1wGRg5fP7jFyhdhL1ThZgNEwiyuIjp1x/y7mzA5IW/kC7Tos+53nP59ox9MnN5x/gsmtT0eH1HFSP8FL4QYoBUEnnk
  template:
    metadata:
      name: openclaw-secrets
      namespace: openclaw

# Placeholders for additional keys (re-seal to add):
# ANTHROPIC_API_KEY: ""
# OPENAI_API_KEY: ""
# GEMINI_API_KEY: ""
