---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: openclaw-secrets
  namespace: openclaw
spec:
  encryptedData:
    OPENROUTER_API_KEY: AgCZ6Z1+GTtJhExKu0d1YPPlEJQINmPTXmH4sLMNr/KGXQ3+bEHkmsSj6I0/COkH0JYy5EcZ66STJWFSQIQzYIVEeex6XWRtiglep+QWqb4H4ln+6DucLkScs6j35V+YXbyR5/kBDGLVoDR7MnHGmVQHPKAxmqlNkuU70NnuJijiDxn9DS6Txta6pPy2ypqZ0DVVdM2hCLczSTsjUitxBlewO/ilOUW5hjv5ytil/Gig02XmB87SIo8y2wLjuhPPmDRdQ550bMLmTBsVWmXBiLzRXjpSp/XlI74GTUpG/MQwJnNE6lzGel7iAB+/OD38pvSfAcI2imcRZYgfCN7ipZp+z+mWLNelJsRcdV7ljhIapLmk2qHG0p/tsaE/9L9+ESKRHkRHN1Rlfjp+wrDhfdMHaPy37czV/F/8Qmv0+Lf6X50tUBshMsLnuHAMjWh6PJgULw2XxAd/2P0VBo1OxjXKr/VS0hlfBbpN33MpiCVtZ9CeoVRCyZ1oJHCMntH0q0uRNgHDBcyAmiX7F+Omy0CVqRlA5/0ZATjfzWAnsWTayXARIxsCj3JLI7K+cd1xxTzE2cdHOurg6JJLhBzoayWzenTe4A3rdfJbZeX82ws/GRQFf/yc0yKg68vZVCht8QhTnvEvgMM5Af8Hk1rW3IXlqFYjdcBR2pWCRnLi8TctvRelOsBp/39801CtzAhScq425B1gKuEwjnGRBbFoQiupDX38iOqQg1Pn+8Nj+vS2JFVWN9E943rejM8pOcYl2J3VSkbvAsGwCP2KnCLgZaHOmhbrE1yGEzqW
  template:
    metadata:
      name: openclaw-secrets
      namespace: openclaw

# Placeholders for additional keys (re-seal to add):
# ANTHROPIC_API_KEY: ""
# OPENAI_API_KEY: ""
# GEMINI_API_KEY: ""
