---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: openclaw-secrets
  namespace: openclaw
spec:
  encryptedData:
    OPENCLAW_GATEWAY_TOKEN: AgAmV541HCRkFroXaBxR1Fj/7cfyr5PJpC1l/N7lWIsPGO2kLU+g89Ge9zYvZ4pB2iDGk8e8a3Oz61wtLI3iwePvv0vD4D+ppSfysERoEgU5MWS88iPHVDbhL45tIsYUGgMhcHuerupgSsDOp/jZz11UFeByrVwvkMil8oZuFuhNeXelBA9XbO7SttQT1dp8nWyXIjwHRce4W4kYKECXqFRtW3iFU7IqltnkjN1J1WOkG8AYthWA2Fk4sSyrouwUdy3XdzZWfad074jzlSOKynFaHjIv9pMwC8IjuoKS46XD20QPb/+D0Uk1C85NQ8WjunpnEth3SwUcSVkaVv4qbXZqIyzBqVtm1G2rs5Akai3sfH5AuW5DRyock3Ll/L2hKl9w4ddrx1FyHcItDBNo6fEZT5MWZaugZ/ckzBrzW6P6JrF5tpM6JRDhysSkCqlWQcojOd0INiVgPUs5anMFfDzc8c33Rq58w4+3bJsRF2vykaFrz67i5N9BsPfFseSNjCArsPtKwx9gZ8JEGZBR6YIoMgeHELMBqj5GMEUyxuJrnK0uh3HRCpIJC1NU/y6wbOslSNzZoVUeGqtz23qsvjhOKOyFyZVmo4GMotpLeWrZRhbh1PEMkQXFoYzzot789uVhq7MJ8ylQJaueUhkXCee0i0Kefm6+NfmXtDc2p18qxzMc6rBNtEA1/nMHb8jq/Rr+i4eei7AuKSVxknE1rDsnakSbQqCAHH+rGX333L4TSHTAjEfb8WzSLC11YgwrqckWNtxlxGdyEUPRbEeXRuPA
    OPENROUTER_API_KEY: AgCZ6Z1+GTtJhExKu0d1YPPlEJQINmPTXmH4sLMNr/KGXQ3+bEHkmsSj6I0/COkH0JYy5EcZ66STJWFSQIQzYIVEeex6XWRtiglep+QWqb4H4ln+6DucLkScs6j35V+YXbyR5/kBDGLVoDR7MnHGmVQHPKAxmqlNkuU70NnuJijiDxn9DS6Txta6pPy2ypqZ0DVVdM2hCLczSTsjUitxBlewO/ilOUW5hjv5ytil/Gig02XmB87SIo8y2wLjuhPPmDRdQ550bMLmTBsVWmXBiLzRXjpSp/XlI74GTUpG/MQwJnNE6lzGel7iAB+/OD38pvSfAcI2imcRZYgfCN7ipZp+z+mWLNelJsRcdV7ljhIapLmk2qHG0p/tsaE/9L9+ESKRHkRHN1Rlfjp+wrDhfdMHaPy37czV/F/8Qmv0+Lf6X50tUBshMsLnuHAMjWh6PJgULw2XxAd/2P0VBo1OxjXKr/VS0hlfBbpN33MpiCVtZ9CeoVRCyZ1oJHCMntH0q0uRNgHDBcyAmiX7F+Omy0CVqRlA5/0ZATjfzWAnsWTayXARIxsCj3JLI7K+cd1xxTzE2cdHOurg6JJLhBzoayWzenTe4A3rdfJbZeX82ws/GRQFf/yc0yKg68vZVCht8QhTnvEvgMM5Af8Hk1rW3IXlqFYjdcBR2pWCRnLi8TctvRelOsBp/39801CtzAhScq425B1gKuEwjnGRBbFoQiupDX38iOqQg1Pn+8Nj+vS2JFVWN9E943rejM8pOcYl2J3VSkbvAsGwCP2KnCLgZaHOmhbrE1yGEzqW
  template:
    metadata:
      name: openclaw-secrets
      namespace: openclaw

# Placeholders for additional keys (re-seal to add):
# ANTHROPIC_API_KEY: ""
# OPENAI_API_KEY: ""
# GEMINI_API_KEY: ""
