apiVersion: v2
name: actual-budget
description: A local-first personal finance system
type: application
version: 0.1.0
appVersion: "26.4.0" # Based on latest release as of now
dependencies:
  - name: common
    version: 0.1.0
    repository: "file://../../common"
