apiVersion: apps/v1
kind: Deployment
metadata:
  name: uptime-kuma
  namespace: {{ .Release.Namespace }}
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: uptime-kuma
  template:
    metadata:
      labels:
        app: uptime-kuma
    spec:
      securityContext:
        fsGroup: {{ .Values.PGID | default 2000 }}
        fsGroupChangePolicy: OnRootMismatch
      containers:
        - name: uptime-kuma
          image: "{{ .Values.images.app.repository }}:{{ .Values.images.app.tag }}"
          imagePullPolicy: {{ .Values.images.app.pullPolicy }}
          ports:
            - containerPort: 3001
              name: http
          env:
            - name: TZ
              value: {{ .Values.TZ | default "UTC" }}
          volumeMounts:
            - name: data
              mountPath: /app/data
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: uptime-kuma-data
