---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: netbird-mgmt-api-key
  namespace: netbird
spec:
  encryptedData:
    NB_API_KEY: AgB3e2amFVavphSs2HFobBol3ELgso7Nkkb4JprZl8MbVbRO19+rDFc3T+cW7MynFI1WubV2VrHR45ZahGw2nXxq0hIDkilTXHHqaSupkkHeVmu6SE5I85R4OrC/DuttLdQtzcLl6o8r3vgfAdCcE0WSAIPNalXXEYlnROxuyIxGOkiU5vXABGi7g/q5F7L00J6zO755rxtoW0yD82bSM9/wHzNFv7Al+c9kCUF/nYiYwqz9fVkgmIcAjGZ4iB6kZeeknW7asR3RX5CDPiXYRUNNcdtclqAzlrmyfXGMXPb6NdtdGgJe7z8iqzeNIhNnv1J8QIw6kcEpHI5KJXy2i3VsM4YupR+qAoeljbWRAn6GC3C5eU7goUzHl9U2YsFjXxO2xlrvDIWfG375RfhmqKeqtFyyv/VuNuYX/XJUYfxuYzjyY7PMoLryDGxzuSHR0whCGCxgPdH0RlsOCQkz//qx7GnvcMI8nLBF2/wIbGdVE5BaVUdV/q7U1qPoyj0+9lLhi3oejl5vWffiLHtJ7Uhxtu5buD9mYrfI/sT66Fuqyl20OH76e5WW4Pkapt7mEL4kidWxo6RrqhF5QpWcuz+9FntIgdIN8pfnXiQABpQjqo2jOZaviJIPU+1xcskjpUcEr0JBOYA9roKfyhfGZ8z/Bp1uE5QvIkynzSe1OWKQk/oTpnvHUf7r/uENvDRjmok2UeT43oc75/C+SkNmGR4oO+UyXbaJpXU/RbDCHqEfF7AsZNCK+CMp
  template:
    metadata:
      name: netbird-mgmt-api-key
      namespace: netbird
