---
- name: All hosts
  hosts: all:!openwrt
  become: true
  roles:
    - ssh-access

- name: Storage
  hosts: storage
  become: true
  roles:
    - mdns
    - users
    - storage

- name: Openwrt
  hosts: openwrt
  roles:
    - dns-openwrt
