---
- name: All hosts
  hosts: all:!openwrt
  roles:
    - ssh-access
    - mdns
    - system

- name: Storage
  hosts: storage
  roles:
    - storage

- name: Openwrt
  hosts: openwrt
  roles:
    - dns-openwrt
