- name: Default
  hosts: all
  become: no
  roles:
    - nix-update

- name: DNS
  hosts: all
  connection: local
  tasks:
    - name: Include DNS role
      include_role:
        name: dnsmasq
      when: ansible_hostname is match('dns*')
