---
- name: All hosts
  hosts: all:!openwrt
  roles:
    - ssh-access
    - mdns
    - system

- name: Storage
  hosts: storage
  roles:
    - storage
    - backup-client

- name: Openwrt
  hosts: openwrt
  roles:
    - dns-openwrt

- name: Hestia
  hosts: hestia
  roles:
    - backup-client
