---
- name: All hosts except openwrt
  hosts: all:!openwrt:!proxmox
  roles:
    - ssh-access

- name: All hosts except openwrt and proxmox
  hosts: all:!openwrt:!proxmox
  roles:
    - mdns
    - system

- name: Storage
  hosts: storage
  roles:
    - storage
    - backup-client

- name: Openwrt
  hosts: openwrt
  roles:
    - dns-openwrt

- name: Hestia
  hosts: hestia
  roles:
    - backup-client
