---
- name: Reload NFS exports
  ansible.builtin.command: exportfs -ra
  changed_when: true

- name: Set SELinux context on keyfile
  ansible.builtin.command: restorecon -v /etc/cryptsetup-keys.d/data-disk.key
  changed_when: true
