apiVersion: apps/v1
kind: Deployment
metadata:
  name: sonarr
  namespace: {{ .Release.Namespace }}
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: sonarr
  template:
    metadata:
      labels:
        app: sonarr
    spec:
      containers:
        - name: sonarr
          image: "{{ .Values.images.sonarr.repository }}:{{ .Values.images.sonarr.tag }}"
          imagePullPolicy: {{ .Values.images.sonarr.pullPolicy }}
          ports:
            - containerPort: 8989
          envFrom:
            - configMapRef:
                name: downloads-config
          livenessProbe:
            httpGet:
              path: /
              port: 8989
            initialDelaySeconds: 30
            periodSeconds: 30
          volumeMounts:
            - name: config
              mountPath: /config
            - name: media
              mountPath: /mnt/pool/media
      volumes:
        - name: config
          persistentVolumeClaim:
            claimName: sonarr-config
        - name: media
          nfs:
            server: {{ .Values.storageDNSName }}
            path: /mnt/pool/media
