apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Chart.Name }}-config
  namespace: {{ .Release.Namespace }}
data:
  PAPERLESS_PORT: "8000"
  PAPERLESS_URL: https://paperless.{{ .Values.domain }}
  PAPERLESS_CSRF_TRUSTED_ORIGINS: https://paperless.{{ .Values.domain }}
  PAPERLESS_USE_X_FORWARDED_HOST: "true"
  PAPERLESS_USE_X_FORWARDED_PORT: "true"
  PAPERLESS_PROXY_SSL_HEADER: '["HTTP_X_FORWARDED_PROTO", "https"]'
  PAPERLESS_REDIS: redis://localhost:6379
  PAPERLESS_TIKA_ENABLED: "1"
  PAPERLESS_TIKA_ENDPOINT: http://localhost:9998
  PAPERLESS_TIKA_GOTENBERG_ENDPOINT: http://localhost:3000
  PAPERLESS_OCR_LANGUAGE: eng
  PAPERLESS_TIME_ZONE: {{ .Values.TZ | default "UTC" }}
  PAPERLESS_APPS: "allauth.socialaccount.providers.openid_connect"
  PAPERLESS_SOCIAL_AUTO_SIGNUP: "true"
  PAPERLESS_ADMIN_USER: admin
  PAPERLESS_ADMIN_MAIL: {{ .Values.adminEmail | default "admin@localhost" }}
