apiVersion: pocketid.internal/v1alpha1
kind: PocketIDOIDCClient
metadata:
  name: paperless
  namespace: {{ .Release.Namespace }}
spec:
  isPublic: false
  callbackUrls:
    - https://paperless.{{ .Values.domain }}/accounts/oidc/pocketid/login/callback/
