{
  "kind": "SealedSecret",
  "apiVersion": "bitnami.com/v1alpha1",
  "metadata": {
    "name": "paperless-secrets",
    "namespace": "paperless"
  },
  "spec": {
    "template": {
      "metadata": {
        "name": "paperless-secrets",
        "namespace": "paperless"
      }
    },
    "encryptedData": {
      "PAPERLESS_SECRET_KEY": "AgA9DoZh2Va5DlJVMNMBWmoPWi+BCTtf0GwOcAniptSOSuA8t0/7lD2S2WIH5zpAJJDl+CJp0nzh7DYxEAv6BY6R5Bbpm5nyBBHHdcwvBUEAy5IgRGXG1zzZ4UKJSsVK2ZpG/LNJWhr6E50lPraOmpBba+AhtfrpX0+d77wttYHYXh5bA0rN++6xJ2Xg0F4otcpMfWfsSH7rbKVelM5KsGB4vvs1HEZPzbvEW+bEw3VCCKTLHoA0C8xcuPgkm8bJ7jR+H/MmbVKKR9Do8fIzFlvdL7KE6WbP8BZX0pKpjsBmCSga44FhcuR4EhjoSj77+RCWrmtb52B7x+GA5AD47WxrmM84YxgjB5FAeWUIO38h30IKZ9w46Ccg0sWDOEdF9dWQGDqFg6risaGxpvwx2XVpfr9ZpE/2ue32edCDO8eb8qL5qdmEZzulQsslC5hDpQUcm2cytz1O4k2MCTOcAgUlfLA9rrSrw34MfKDkSPP2gPN/c9OFd4ZVWAmRBA1HyzeJE2khx8fLE3fC7xtrlBbnJw1GQKIJcoN2Bwy3De7R/FuF48v/QpMG+Vz3NHxK/cdYDTd59NIfbht0dKPJkEgCt3UQDzUIVsaQG0frKZsRx4lC1Zg3vuBuqQ4vZ0I6rlFmwrlitWSDK+8VBG75OBvITftDdOvW3HHXv7WvHLKDRRwnD4kEkng1e+KpDMKbMHxi5OH5BfagLjqpYodaVQBMf5uMRz70BE/S2OfFjfIJfclPJOJeRmFCigqhLg=="
    }
  }
}
