{
  "kind": "SealedSecret",
  "apiVersion": "bitnami.com/v1alpha1",
  "metadata": {
    "name": "paperless-secrets",
    "namespace": "paperless"
  },
  "spec": {
    "template": {
      "metadata": {
        "name": "paperless-secrets",
        "namespace": "paperless"
      }
    },
    "encryptedData": {
      "PAPERLESS_SECRET_KEY": "AgA/aNSWXNOe7b5p6J7RXPfHE4qCDeXFz9h2DOaNzRF0e4eSzoUiZifowKvyNk1nO0749em7eOyWfGLM2LrrNGhg0aRwnsBAgUaD/oyl4gm6GS9RjhH71t/otvNtnfgtRvxmknpi1M0G/jyVcKBpeROEwC0faIONjHKYvTbwtXdJe7so7W2RGV8AZL0LUPsKTUXAUZQxM7dolOGYx+/1Q11iPT6cR04ahN56MQEqt1b1h1Vi6iclAGcXB8ZZedKz8tjJT8XvbPipc9C7Q9yYUxXweMluNba8hs3klOZfqRu2OEbTtKY9XMgV/5WiZr6gxmbVu9XL78QMihOPUiw+G4dKzInUiKAy7s5DRMfLQFtG11zJ+iq82VKL5M93uYTyG/fvx77G/p5YHRfBynQNYcWO29batlvMhNtLgSn06slZrBP28Ki1t2LfuJrPyeTmAEjxkHpMsP/pVCMXDhLOuN3T/k6KsLsWtp2ebjuLbr5gp7dRQYZ+YyhlQK0Zcsux7gdiY6Z24t9oytnMN6qbJMmupcgZ/uBSa5Zm5NZyk16J/8Tfb22KC0yvJRvKhIomfJl4whtW7kBb7fWKwY4I1laIOhChOidfRuO2O62MLKXjYnDJU2nLpbOJNVBt25/Aygg61Sen+m/ONHUhIyIo9W+dgNazqKzGsNUo9SZc+ucE5Lg2hIbc9322Oh5+OvDL8HZV6jKqtPay+HZpdCHgWWCNutvFhWqCrC5NnS2u8rgVLq+yPT4g5mh+KRPSnQ=="
    }
  }
}
