{
  "kind": "SealedSecret",
  "apiVersion": "bitnami.com/v1alpha1",
  "metadata": {
    "name": "paperless-secrets",
    "namespace": "paperless"
  },
  "spec": {
    "template": {
      "metadata": {
        "name": "paperless-secrets",
        "namespace": "paperless"
      }
    },
    "encryptedData": {
      "PAPERLESS_ADMIN_PASSWORD": "AgC+8CvTLvkCUcgV1seXn+0ax1/FFq+uuzD0QnkboBrz5EH41xr5NiQwjJ9fwh+ZdLhcSm0s5/OpWJPF4j/TCgMuE8BJhQORxbL5sYEp4Xb03ksOMrCyinGoz1goEsdGFU7GMRc7haFhi35655cXKysmfqkkGYeVfzdCM+MKmmOFJ+AEbwNnBH0ynG4tslgdR/lwqlMcNNwvKet+QQ6C3upRVuvZRy53PlwNp1PTF8k0hOpAH+7ztKxynyKuYyr57iXUHxMfO4xhB/BrLtVXD2jbTNXzZICtlfKCk4Wop3T4ZqVCRzzAQRcBW1KenA1Onxclyl7Nht3ggJiP8FJonAtT3ATgZ6qdyqr6fdTGWJ5UclNBIjpc4Vxf4ApQsM3kZMNv0dlqF2YMwcMm16iw+k8iTgQ82LUJVtUwTE6Hh2ypyN4zrLYFQFzEkWV8T2zynccAwxJXl5PMszN94VniDemmACD1sikOFSY/ZI3r4R2dVNN6sfgjBkhfWMcptD4hAu8NO1G1M5ew/AdPq17JqEICw/8IqczravRjM26tjKXuBWIPWbkm7DMnumwxKJUPt25lMqMujj/1Ya8yCPG0NLqzL4rZs/eJZ0sHKJVahxh+5R//21sHKwxRDrO+opIrehzLvy/Apl1oDhq3MiCnWMpdumFhhZUt0slvdIh9y5g3aJB4Bba0TNnOHa7HgWpRx1/7FAmNOj1LeeisYYppT1tRJReRmxhWHgrac1hvkD5++Q==",
      "PAPERLESS_SECRET_KEY": "AgC41EjxBZLr6oMuhqRgK/dLYk1Bw1gptzy9V/Vq2fNAQwei4/zPVU2UwLpD1K1O60ee/XXymXUKsaDKhp6QwzpkHuEtyveCsFEBv/ejEF8y0zf04dlKaqzcT0AyUJXjMvwdDsrilIIZPleQQMN94Vw4uihYE9QL/LE7MfkXmUCE9YX8EDCnB+ovqz0RTgEERTxgkh7cP1u+X9TJ8IcNGaiqdyFEmc9qDUu1rjFcVMWe2MjckNKMXcA3pG0AOGFnUpZ64IEYeVCcVTpLpaCEqBGqjPBdi5nhzpxwQH0SZ53PvI42cA4QCzvJbH+4S/nLSzStnoSFM0TfOupwpQSrQNeub2psjQ2lc1lAi9FSDx8PxYQX9JkHshkb6ndt+fWO167e4dFdED2I/1pkvF4jYV4Ltr/woIfXwK/zohez5FcF+/c9Hx9G0LQ6UmIJabzBQCxMn/V5xSuazqsbvnTepNE/Rl9AEFVumhocNVnILpCFG3gonkLeUK+vb4E1GZQhzBQukmJRbGqljm/3ijHLi9WzlP4LoMJVQI45yFpk/Xbp/2N5YQEKphHy3XTQ5COE/vANqE0UqI7I+wUI+ttBTx6tJPLkC8PmGzbZ1a3UO91np2Jcy7O//fqrKflTtBIPWhTFgzoLMGE9CdEj1/yQdIAM5cGQGv54FmO3BXkpgMHeiDw+DaWARM+99PwHeIADrAAFU0RIbxglBvKe1Cdk5aOGI0mgMlzamx1RQtUNOTiKCaWqTDKeC3itXec6Vg=="
    }
  }
}
