{{ include "common.pomeriumIngress" (dict
  "ctx" .
  "name" "argocd"
  "subdomain" "argocd"
  "port" 80
  "allowedUsers" "admin"
) }}
---
{{ include "common.pomeriumIngress" (dict
  "ctx" .
  "name" "argocd-webhook"
  "subdomain" "argocd"
  "port" 80
  "path" "/api/webhook"
  "type" "public"
  "allowedUsers" "all"
) }}
