---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: argocd-webhook-secret
  namespace: argocd
spec:
  encryptedData:
    webhook.github.secret: AgAiJkCX95Niyd9AdEtzveTeyOM5/TuSrm3rKolR2qmuoJ3vac7mG4gw0o7y0Kk82vEQM2LhBVpjZtNI2CtZttvgzK11WCpMTu56aHPpGv8z0eDoN09lOFVXqpBO1KKccEcdKb/RdH9SGSHYf1e64EhGyKJUOtJ7j9Gb7ug3tGZZ3L2Mo3prwva9YFpmfme4AmwZ3587SpYvHcioleKZduNGyVvNj7EbfG415W/HvBz+QRl0/m1INbziP0GnLrzecfuc0fpzlWyCDUKIwPerU0wRYe/o8CNWoRyBk7hNkEGE6dEp5DnVRn6Au2X89d2wfaHMhXTOKbX8by7AmVYYl6DFMCNwQjX7eFcENF4FE1TpAFmESjsZ8cuPDbSdFLGW4p3Yx6PXeht8Dkazf2HKm4Z51TB0NjOP8+Ogjd+2+vwX9zsvaCrQ/klMCRNTOHL2Yi3FxnbvG60PDoYOyUgfIWAGh2USrOJa2NLReGcOw7oV48D2+Qiywn19phCzRTSx5ew7A8HSSVDOPsxgJ3p+TAtQRsxEYJvMO7efOZf4Pv2C9zzmtlzoxdxj1eAoyUTkr9oYLnyYrKlAtzq4qVjyIIgCXv/OoXdMzl8z/k2CeUvfiVQyGgr03Z4vLmjhgSvCgoblDt3k704Ct/fI2oylo6wrm/R28piLK/LqgxawfAemRrctK7qW6fSPvYC3k5sOZXOq2YV65yV011oTsyfmRxsfuLA6LLRvLxqhRM9MDgJOGGzykFPUxK/pBq1mIg==
  template:
    metadata:
      name: argocd-webhook-secret
      namespace: argocd
