---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: argocd-webhook-secret
  namespace: argocd
  labels:
    app.kubernetes.io/part-of: argocd
spec:
  encryptedData:
    webhook.github.secret: AgAiJkCX95Niyd9AdEtzveTeyOM5/TuSrm3rKolR2qmuoJ3vac7mG4gw0o7y0Kk82vEQM2LhBVpjZtNI2CtZttvgzK11WCpMTu56aHPpGv8z0eDoN09lOFVXqpBO1KKccEcdKb/RdH9SGSHYf1e64EhGyKJUOtJ7j9Gb7ug3tGZZ3L2Mo3prwva9YFpmfme4AmwZ3587SpYvHcioleKZduNGyVvNj7EbfG415W/HvBz+QRl0/m1INbziP0GnLrzecfuc0fpzlWyCDUKIwPerU0wRYe/o8CNWoRyBk7hNkEGE6dEp5DnVRn6Au2X89d2wfaHMhXTOKbX8by7AmVYYl6DFMCNwQjX7eFcENF4FE1TpAFmESjsZ8cuPDbSdFLGW4p3Yx6PXeht8Dkazf2HKm4Z51TB0NjOP8+Ogjd+2+vwX9zsvaCrQ/klMCRNTOHL2Yi3FxnbvG60PDoYOyUgfIWAGh2USrOJa2NLReGcOw7oV48D2+Qiywn19phCzRTSx5ew7A8HSSVDOPsxgJ3p+TAtQRsxEYJvMO7efOZf4Pv2C9zzmtlzoxdxj1eAoyUTkr9oYLnyYrKlAtzq4qVjyIIgCXv/OoXdMzl8z/k2CeUvfiVQyGgr03Z4vLmjhgSvCgoblDt3k704Ct/fI2oylo6wrm/R28piLK/LqgxawfAemRrctK7qW6fSPvYC3k5sOZXOq2YV65yV011oTsyfmRxsfuLA6LLRvLxqhRM9MDgJOGGzykFPUxK/pBq1mIg==
  template:
    metadata:
      name: argocd-webhook-secret
      namespace: argocd
      labels:
        app.kubernetes.io/part-of: argocd
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: argocd-server-secret
  namespace: argocd
  labels:
    app.kubernetes.io/part-of: argocd
spec:
  encryptedData:
    server.secretkey: AgBNq8oGE3wz85nxzEo5m/Go+1Lvqfa7kMsgmbuATnaRzD3Nt7fvFaierbMpjdmAOpPOki61RcxylzM/W/kWvybL0Mcm0zIbhxJHSFIDQH32TSM0o1ehu8jMHFbot4V1hPV4zLXoXfjY/Hd6cudpr6nAouNbeeanw0IpIkL5CR+V2I4D7rvX1LQUdE1nEtOImzMO6WbqgzYX3pQUPtxaqumYfxKW+7wcAydRLNLuCynzxzTgr/V++qDpHgDt0WER59Cizryzw29h+t/1CYaKfR4pHM5QzOL1Yd9134wCZcm97AlNbFh5i4E8nwPEgGJLZGLw5AbDoMgjJuWKVpkOirA4bVy1Cjr8Sxt3599NF+XcIt04Pz6n4gyhN/fWV6J/fD1fiNUvDcVTj5iJrIFoemwGZXNlts+1oHJWKlwvxPUDvTRZMeDK1RmSvmKo2KFoXAtkxR/HGMKOOJBE/8H4zOvRxoIkhKFFLqDl8wIsGvij6/4dDD4BJI/NSejchErgI+tr9K6kWe3SsBvYliOdE5xem8+miQKz7/dRxFnx20Tv9LG/q38a0pMQB1/PqWxnL3I7JqwYfNF78iQFlOVOZjaKXXWIDP5dCHIEOosO67cXKqFNyrrUo1TzabOt29Q2AbmvljsKp0mO80aDEVd0m5sUU6h3x5vJb94P5cgjR4SCZUGHqN+dMi2ghMDG8WE4x5NrYgjcm7q0bFYVWmkSvR9NlwLJNQiG24Y222zTtk1JYMeIBgI6xrt8qZO/Dg==
  template:
    metadata:
      name: argocd-server-secret
      namespace: argocd
      labels:
        app.kubernetes.io/part-of: argocd
