apiVersion: autoscaling.k8s.io/v1
kind: VerticalPodAutoscaler
metadata:
  name: argo-cd-server
  namespace: {{ .Release.Namespace }}
spec:
  targetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: argo-cd-argocd-server
  updatePolicy:
    updateMode: "InPlaceOrRecreate"
    minReplicas: 1
---
apiVersion: autoscaling.k8s.io/v1
kind: VerticalPodAutoscaler
metadata:
  name: argo-cd-repo-server
  namespace: {{ .Release.Namespace }}
spec:
  targetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: argo-cd-argocd-repo-server
  updatePolicy:
    updateMode: "InPlaceOrRecreate"
    minReplicas: 1
---
apiVersion: autoscaling.k8s.io/v1
kind: VerticalPodAutoscaler
metadata:
  name: argo-cd-application-controller
  namespace: {{ .Release.Namespace }}
spec:
  targetRef:
    apiVersion: apps/v1
    kind: StatefulSet
    name: argo-cd-argocd-application-controller
  updatePolicy:
    updateMode: "InPlaceOrRecreate"
    minReplicas: 1
---
apiVersion: autoscaling.k8s.io/v1
kind: VerticalPodAutoscaler
metadata:
  name: argo-cd-applicationset-controller
  namespace: {{ .Release.Namespace }}
spec:
  targetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: argo-cd-argocd-applicationset-controller
  updatePolicy:
    updateMode: "InPlaceOrRecreate"
    minReplicas: 1
---
apiVersion: autoscaling.k8s.io/v1
kind: VerticalPodAutoscaler
metadata:
  name: argo-cd-redis
  namespace: {{ .Release.Namespace }}
spec:
  targetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: argo-cd-argocd-redis
  updatePolicy:
    updateMode: "InPlaceOrRecreate"
    minReplicas: 1
