radarrVolumeSizeGi: 5
sonarrVolumeSizeGi: 5
prowlarrVolumeSizeGi: 1
sabnzbdVolumeSizeGi: 1
qbittorrentVolumeSizeGi: 1
seerrVolumeSizeGi: 5
quiVolumeSizeGi: 1
shelfmarkVolumeSizeGi: 1

images:
  shelfmark:
    repository: ghcr.io/calibrain/shelfmark
    tag: v1.3.0
    pullPolicy: IfNotPresent
  seerr:
    repository: ghcr.io/seerr-team/seerr
    tag: v3.2.0
    pullPolicy: IfNotPresent
  sonarr:
    repository: lscr.io/linuxserver/sonarr
    tag: 4.0.17
    pullPolicy: IfNotPresent
  radarr:
    repository: lscr.io/linuxserver/radarr
    tag: 6.1.1
    pullPolicy: IfNotPresent
  sabnzbd:
    repository: lscr.io/linuxserver/sabnzbd
    tag: 5.0.3
    pullPolicy: IfNotPresent
  prowlarr:
    repository: lscr.io/linuxserver/prowlarr
    tag: 2.3.5
    pullPolicy: IfNotPresent
  qbittorrent:
    repository: lscr.io/linuxserver/qbittorrent
    tag: 5.2.0-libtorrentv1
    pullPolicy: IfNotPresent
  wireguard:
    repository: jordanpotter/wireguard
    tag: 2026-03-24
    pullPolicy: IfNotPresent
