images:
  teslamate:
    repository: teslamate/teslamate
    tag: "3.0.0"
    pullPolicy: IfNotPresent
  grafana:
    repository: teslamate/grafana
    tag: "3.0.0"
    pullPolicy: IfNotPresent
  mosquitto:
    repository: eclipse-mosquitto
    tag: "2"
    pullPolicy: IfNotPresent

grafanaVolumeSizeGi: 1
mqttVolumeSizeGi: 1
databaseVolumeSizeGi: 5
