apiVersion: v1
kind: ConfigMap
metadata:
  name: immich-config
  namespace: {{ .Release.Namespace }}
data:
  TZ: {{ .Values.TZ }}
  IMMICH_PORT: "2283"
  REDIS_PORT: "6379"
  REDIS_HOSTNAME: redis.{{ .Release.Namespace }}.svc.cluster.local
