apiVersion: apps/v1
kind: Deployment
metadata:
  name: syncthing
  namespace: {{ .Release.Namespace }}
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: syncthing
  template:
    metadata:
      labels:
        app: syncthing
    spec:
      securityContext:
        fsGroup: {{ .Values.PGID }}
        fsGroupChangePolicy: OnRootMismatch
      containers:
        - name: syncthing
          image: "{{ .Values.images.app.repository }}:{{ .Values.images.app.tag }}"
          imagePullPolicy: {{ .Values.images.app.pullPolicy }}
          ports:
            - containerPort: 8384
              hostPort: 8384
              name: web
            - containerPort: 22000
              hostPort: 22000
              name: sync-tcp
            - containerPort: 22000
              hostPort: 22000
              protocol: UDP
              name: sync-udp
            - containerPort: 21027
              hostPort: 21027
              protocol: UDP
              name: discovery
          env:
            - name: TZ
              value: {{ .Values.TZ }}
            - name: PUID
              value: {{ .Values.PUID | quote }}
            - name: PGID
              value: {{ .Values.PGID | quote }}
          livenessProbe:
            httpGet:
              port: 8384
              path: /
            initialDelaySeconds: 30
          readinessProbe:
            httpGet:
              port: 8384
              path: /
            initialDelaySeconds: 10
          volumeMounts:
            - name: config
              mountPath: /config
            - name: data
              mountPath: /data
      volumes:
        - name: config
          persistentVolumeClaim:
            claimName: syncthing-config
        - name: data
          nfs:
            server: {{ .Values.network.storage }}
            path: {{ .Values.appStoragePath }}/syncthing
