apiVersion: v1
kind: Service
metadata:
  name: syncthing
  namespace: {{ .Release.Namespace }}
  labels:
    app: syncthing
spec:
  selector:
    app: syncthing
  ports:
    - port: 8384
      targetPort: 8384
