apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: longhorn-v2
provisioner: driver.longhorn.io
allowVolumeExpansion: true
reclaimPolicy: Retain
volumeBindingMode: Immediate
parameters:
  numberOfReplicas: {{ .Values.storageClassV2.replicas | default 1 | quote }}
  dataEngine: "v2"
  fsType: "ext4"
  dataLocality: "best-effort"
  backupTargetName: "default"
  unmapMarkSnapChainRemoved: "ignored"
  disableRevisionCounter: "true"
