apiVersion: v1
kind: ServiceAccount
metadata:
  name: cordon-sync
  namespace: {{ .Release.Namespace }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: cordon-sync
rules:
  - apiGroups: [""]
    resources: ["nodes"]
    verbs: ["get", "list", "watch", "patch", "update"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: cordon-sync
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cordon-sync
subjects:
  - kind: ServiceAccount
    name: cordon-sync
    namespace: {{ .Release.Namespace }}
