apiVersion: apps/v1
kind: Deployment
metadata:
  name: grafana
  namespace: {{ .Release.Namespace }}
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: grafana
  template:
    metadata:
      labels:
        app: grafana
    spec:
      securityContext:
        fsGroup: 472
      containers:
        - name: grafana
          image: "{{ .Values.images.grafana.repository }}:{{ .Values.images.grafana.tag }}"
          imagePullPolicy: {{ .Values.images.grafana.pullPolicy }}
          ports:
            - containerPort: 3000
              name: http
          env:
            - name: GF_SERVER_ROOT_URL
              value: https://teslamate-grafana.{{ .Values.domain }}
            - name: GF_AUTH_GENERIC_OAUTH_ENABLED
              value: "true"
            - name: GF_AUTH_GENERIC_OAUTH_NAME
              value: PocketID
            - name: GF_AUTH_GENERIC_OAUTH_SCOPES
              value: openid profile email
            - name: GF_AUTH_GENERIC_OAUTH_USE_PKCE
              value: "true"
            - name: GF_AUTH_GENERIC_OAUTH_CLIENT_ID
              valueFrom:
                secretKeyRef:
                  name: grafana-oidc-credentials
                  key: client_id
            - name: GF_AUTH_GENERIC_OAUTH_CLIENT_SECRET
              valueFrom:
                secretKeyRef:
                  name: grafana-oidc-credentials
                  key: client_secret
            - name: GF_AUTH_GENERIC_OAUTH_AUTH_URL
              valueFrom:
                secretKeyRef:
                  name: grafana-oidc-credentials
                  key: authorization_url
            - name: GF_AUTH_GENERIC_OAUTH_TOKEN_URL
              valueFrom:
                secretKeyRef:
                  name: grafana-oidc-credentials
                  key: token_url
            - name: GF_AUTH_GENERIC_OAUTH_API_URL
              valueFrom:
                secretKeyRef:
                  name: grafana-oidc-credentials
                  key: userinfo_url
            - name: DATABASE_USER
              valueFrom:
                secretKeyRef:
                  name: teslamate-db-app
                  key: user
            - name: DATABASE_PASS
              valueFrom:
                secretKeyRef:
                  name: teslamate-db-app
                  key: password
            - name: DATABASE_NAME
              value: teslamate
            - name: DATABASE_HOST
              value: teslamate-db-rw
          volumeMounts:
            - name: grafana-data
              mountPath: /var/lib/grafana
      volumes:
        - name: grafana-data
          persistentVolumeClaim:
            claimName: teslamate-grafana-data
