name: Update cluster

on:
  push:
    branches:
      - main
    paths:
      - "talos/**"
  workflow_dispatch:

env:
  AWS_REGION: us-east-1
  NIX_PATH: nixpkgs=https://github.com/NixOS/nixpkgs/archive/nixos-unstable.tar.gz

permissions:
  id-token: write
  contents: read

concurrency:
  group: update-cluster
  cancel-in-progress: false

jobs:
  update-cluster:
    runs-on: ubuntu-latest
    timeout-minutes: 90
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Setup environment
        uses: ./.github/actions/setup-environment
        with:
          wireguard-endpoint: ${{ secrets.WIREGUARD_ENDPOINT }}
          wireguard-endpoint-public-key: ${{ secrets.WIREGUARD_ENDPOINT_PUBLIC_KEY }}
          wireguard-ips: ${{ secrets.WIREGUARD_IPS }}
          wireguard-allowed-ips: ${{ secrets.WIREGUARD_ALLOWED_IPS }}
          wireguard-private-key: ${{ secrets.WIREGUARD_PRIVATE_KEY }}
          wireguard-preshared-key: ${{ secrets.WIREGUARD_PRESHARED_KEY }}

      - name: Check Talos version and upgrade if needed
        run: nix-shell --run 'scripts/upgrade-talos'

      - name: Check Kubernetes version and upgrade if needed
        run: nix-shell --run 'scripts/upgrade-k8s'

      - name: Apply Talos config
        run: nix-shell --run 'scripts/apply-talos'
