apiVersion: v2
name: dns
description: DNS services - PiHole + External DNS + Cloudflare DDNS
version: 0.1.0
dependencies:
  - name: external-dns
    version: 1.21.1
    repository: https://kubernetes-sigs.github.io/external-dns/
    alias: external-dns-pihole
  - name: external-dns
    version: 1.21.1
    repository: https://kubernetes-sigs.github.io/external-dns/
    alias: external-dns-cloudflare
  - name: common
    version: 0.1.0
    repository: "file://../../common"
