external-dns-pihole:
  txtOwnerId: external-dns-pihole
  policy: sync
  registry: noop
  sources:
    - ingress
    - traefik-proxy
    - service
  provider:
    name: pihole
  extraArgs:
    - --ingress-class=traefik-private
    - --pihole-server=http://pihole-web.dns.svc.cluster.local
    - --pihole-api-version=6

external-dns-cloudflare:
  txtOwnerId: external-dns-cloudflare
  policy: sync
  sources:
    - ingress
    - traefik-proxy
  provider: cloudflare
  extraArgs:
    - --ingress-class=traefik-public
  env:
    - name: CF_API_TOKEN
      valueFrom:
        secretKeyRef:
          name: cloudflare-api-token
          key: api-token

piholeVolumeSizeGi: 1

images:
  ddns:
    repository: favonia/cloudflare-ddns
    tag: latest
    pullPolicy: Always
  pihole:
    repository: pihole/pihole
    tag: 2026.04.0
    pullPolicy: IfNotPresent
