external-dns-pihole:
  txtOwnerId: external-dns-pihole-primary
  policy: sync
  registry: noop
  sources:
    - ingress
    - service
    - crd
  provider:
    name: pihole
  extraArgs:
    - --annotation-prefix=dns.internal/
    - --annotation-filter=dns.internal/enabled=true
    - --ingress-class=pomerium
    - --pihole-server=http://pihole-web.dns.svc.cluster.local

external-dns-pihole-secondary:
  txtOwnerId: external-dns-pihole-secondary
  policy: sync
  registry: noop
  sources:
    - ingress
    - service
    - crd
  provider:
    name: pihole
  extraArgs:
    - --annotation-prefix=dns.internal/
    - --annotation-filter=dns.internal/enabled=true
    - --ingress-class=pomerium
    - --pihole-server=http://pihole-secondary-web.dns.svc.cluster.local

external-dns-cloudflare:
  txtOwnerId: external-dns-cloudflare
  policy: sync
  sources:
    - ingress
    - service
    - crd
  provider: cloudflare
  extraArgs:
    - --annotation-prefix=dns.external/
    - --annotation-filter=dns.external/enabled=true
    - --ingress-class=pomerium
  env:
    - name: CF_API_TOKEN
      valueFrom:
        secretKeyRef:
          name: cloudflare-api-token
          key: api-token

images:
  ddns:
    repository: favonia/cloudflare-ddns
    tag: latest
    pullPolicy: Always
  pihole:
    repository: pihole/pihole
    tag: 2026.09.0
    pullPolicy: IfNotPresent
